gravitee-io/gravitee-node

gravitee-node-management/src/main/java/io/gravitee/node/management/http/configuration/ConfigurationEndpoint.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/spring/ManagementConfiguration.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/verticle/ManagementVerticle.java, gravitee-node-management/src/main/resources/META-INF/spring.factories
Closes gravitee-io/issues#1485
=> feat(node): Add endpoint to expose node configuration (gravitee.yml)

gravitee-node-container/pom.xml, gravitee-node-container/src/main/java/io/gravitee/node/container/spring/SpringBasedContainer.java, gravitee-node-notifier/pom.xml, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/NotifierConfigurationFactory.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/NotifierService.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/impl/NotifierServiceImpl.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/internal/NotifierConfigurationFactoryImpl.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/internal/NotifierFactory.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/plugin/NotifierPluginHandler.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/spring/NotifierPluginConfiguration.java, gravitee-node-notifier/src/main/resources/META-INF/spring.factories, gravitee-node-reporter/src/main/java/io/gravitee/node/reporter/vertx/eventbus/EventBusReporterWrapper.java, pom.xml
This closes gravitee-io/issues#63
=> feat: allows to send an alert when the HC status changes

gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/endpoint/ManagementEndpointManagerImpl.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/verticle/ManagementVerticle.java
=> fix(authentication): secure all routes if needed

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/verticle/factory/SpringVerticleFactory.java
This closes gravitee-io/issues#1791
=> fix: Sometimes we reach a class not found on SpringVerticleFactory

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java
Closes gravitee-io/issues#2057
=> fix(metrics): Do not get metrics for particular client / path

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java
Closes gravitee-io/issues#2179
=> feat(metrics): Labels / tags can be configured on a per-label basis

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java
=> fix(vertx): support vertx options as system property

gravitee-node-container/src/main/java/io/gravitee/node/container/spring/SpringBasedContainer.java, gravitee-node-notifier/src/main/resources/META-INF/spring.factories, gravitee-node-services/gravitee-node-services-monitoring/pom.xml, gravitee-node-services/gravitee-node-services-monitoring/src/main/java/io/gravitee/node/service/monitoring/MonitoringService.java, gravitee-node-services/gravitee-node-services-monitoring/src/main/java/io/gravitee/node/service/monitoring/MonitoringThread.java, gravitee-node-services/gravitee-node-services-monitoring/src/main/java/io/gravitee/node/service/monitoring/probe/ProcessProbe.java, gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java, pom.xml
Closes gravitee-io/issues#2777
=> feat(alert): Alerting integration

gravitee-node-api/src/main/java/io/gravitee/node/api/NodeDeployer.java, gravitee-node-container/src/main/java/io/gravitee/node/container/NodeDeployerFactoriesLoader.java, gravitee-node-container/src/main/java/io/gravitee/node/container/NodeFactory.java, gravitee-node-container/src/main/java/io/gravitee/node/container/spring/NodeConfiguration.java, gravitee-node-container/src/main/java/io/gravitee/node/container/spring/SpringBasedContainer.java
Closes gravitee-io/issues#2878
=> feat(node): Add an interface to intercept node instantiation

gravitee-node-plugins/gravitee-node-plugins-service/src/main/java/io/gravitee/node/plugins/service/handler/ServicePluginHandler.java, gravitee-node-reporter/src/main/java/io/gravitee/node/reporter/plugin/ReporterPluginHandler.java
Closes gravitee-io/issues#2880
=> feat(plugin): Move to latest plugin core version

gravitee-node-api/src/main/java/io/gravitee/node/api/utils/NodeUtils.java
=> feat(services): Add a user-agent header for all services requests

gravitee-node-container/src/main/java/io/gravitee/node/container/NodeFactory.java
Closes gravitee-io/issues#2963
=> fix(node): Node instance can be autowired, let's do it for each deployer

gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/NodeHealthcheckService.java
=> fix(prometheus): register HC service only on Prometheus

gravitee-node-jetty/pom.xml, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/JettyHttpConfiguration.java, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/JettyHttpServer.java, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/JettyHttpServerFactory.java, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/handler/NoContentOutputErrorHandler.java, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/healthcheck/JettyHttpServerProbe.java, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/node/JettyNode.java, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/spring/JettyContainerConfiguration.java, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/vertx/VertxCompletableFuture.java, gravitee-node-jetty/src/main/resources/META-INF/spring.factories, pom.xml
Closes gravitee-io/issues#3148
=> feat(node-jetty): Add jetty node base

gravitee-node-services/gravitee-node-services-healthcheck/pom.xml, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/NodeHealthcheckService.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/ProbeStatusRegistry.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/management/HealthcheckManagementEndpoint.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/micrometer/NodeHealthcheckMetrics.java
Closes gravitee-io/issues#3118
=> feat(alert): Push node healthcheck metrics to alert producer

gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/management/HealthcheckManagementEndpoint.java
Closes gravitee-io/issues#3400
=> fix(node): Internal healt-check is returning 500 when healthy

gravitee-node-reporter/src/main/java/io/gravitee/node/reporter/vertx/verticle/ReporterVerticle.java
Closes gravitee-io/issues#3888
=> fix(reporter): Set a default handler when closing reporter

gravitee-node-services/gravitee-node-services-monitoring/src/main/java/io/gravitee/node/service/monitoring/MonitoringThread.java
=> fix: NPE on windows environment when using alerting

gravitee-node-plugins/gravitee-node-plugins-service/src/main/java/io/gravitee/node/plugins/service/handler/ServicePluginHandler.java, gravitee-node-reporter/src/main/java/io/gravitee/node/reporter/plugin/ReporterPluginHandler.java, pom.xml
Closes gravitee-io/issues#4123
=> feat(plugin): Add support for plugin icon and documentation

pom.xml
Closes gravitee-io/issues#4486
=> fix(plugin): Update plugin dependencies

gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/ClusterManager.java, gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/Member.java, gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/MemberListener.java, gravitee-node-cluster/pom.xml, gravitee-node-cluster/src/main/java/io/gravitee/node/cluster/ClusterService.java, gravitee-node-cluster/src/main/java/io/gravitee/node/cluster/hazelcast/HazelcastClusterManager.java, gravitee-node-cluster/src/main/java/io/gravitee/node/cluster/member/NodeMember.java, gravitee-node-cluster/src/main/java/io/gravitee/node/cluster/spring/ClusterConfiguration.java, pom.xml
Closes gravitee-io/issues#4493
=> feat(cluster): Add clustering support capabilities

gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/Member.java, gravitee-node-cluster/src/main/java/io/gravitee/node/cluster/hazelcast/HazelcastClusterManager.java, gravitee-node-cluster/src/main/java/io/gravitee/node/cluster/member/NodeMember.java, gravitee-node-cluster/src/main/java/io/gravitee/node/cluster/spring/ClusterConfiguration.java, pom.xml
=> chore: use hazelcast version from parent pom

gravitee-node-management/src/main/java/io/gravitee/node/management/http/endpoint/ManagementEndpoint.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/configuration/HttpServerConfiguration.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/endpoint/ManagementEndpointManagerImpl.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/spring/HttpServerSpringConfiguration.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/verticle/ManagementVerticle.java
=> feat(kubernetes): addition of AdmissionHook endpoint

gravitee-node-services/gravitee-node-services-healthcheck/pom.xml, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/management/HealthcheckManagementEndpoint.java, gravitee-node-services/gravitee-node-services-healthcheck/src/test/java/io/gravitee/node/service/healthcheck/management/HealthcheckManagementEndpointTest.java, gravitee-node-services/gravitee-node-services-healthcheck/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, pom.xml
Fixes https://github.com/gravitee-io/issues/issues/5236
=> feat: allow to filter probes on health resource

gravitee-node-api/src/main/java/io/gravitee/node/api/healthcheck/ProbeManager.java, gravitee-node-api/src/main/java/io/gravitee/node/api/healthcheck/Result.java, gravitee-node-management/src/main/java/io/gravitee/node/management/healthcheck/ProbeManagerImpl.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/spring/ManagementConfiguration.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/NodeHealthcheckService.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/ProbeStatusRegistry.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/spring/NodeHealthcheckConfiguration.java
=> feat: allow to detect when the gateway is up vs when it is ready

gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/NodeHealthcheckService.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/management/HealthcheckManagementEndpoint.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/probe/CPUProbe.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/probe/MemoryProbe.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/probe/internal/JvmInfo.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/probe/internal/JvmProbe.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/probe/internal/ProcessProbe.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/java/io/gravitee/node/service/healthcheck/spring/NodeHealthcheckConfiguration.java, gravitee-node-services/gravitee-node-services-healthcheck/src/main/resources/META-INF/spring.factories, gravitee-node-services/gravitee-node-services-healthcheck/src/test/java/io/gravitee/node/service/healthcheck/management/HealthcheckManagementEndpointTest.java
Fixes https://github.com/gravitee-io/issues/issues/4903
=> feat: resource information in health API

.circleci/config.yml
Tests 
* release dry run on PR source branch : 
* first success: https://app.circleci.com/pipelines/github/gravitee-io/graviteeio-node/98/workflows/42ffec5e-0aaf-476a-9c77-1c24f46f428e/jobs/105
* needs a second success after work is finished by dev team + rebase on `master`
=> Circle CI Standalone release

gravitee-node-api/src/main/java/io/gravitee/node/api/monitor/JvmInfo.java, gravitee-node-api/src/main/java/io/gravitee/node/api/monitor/Monitor.java
Related to issue https://github.com/gravitee-io/gravitee-cockpit/issues/490
=> feat(): add empty constructor necessary for deserialization

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java
=> feat(vertx): enable native transport.

gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/NodeHealthCheckThread.java
Closes gravitee-io/issues#5764
=> fix(probe): set probe status to "noReady" when starting

gravitee-node-api/src/main/java/io/gravitee/node/api/tracing/Tracer.java, gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/NodeHealthCheckService.java, gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/infos/NodeInfosService.java, gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/monitor/NodeMonitorService.java, gravitee-node-reporter/src/main/java/io/gravitee/node/reporter/vertx/verticle/ReporterVerticle.java, gravitee-node-tracing/pom.xml, gravitee-node-tracing/src/main/java/io/gravitee/node/tracing/LazyTracer.java, gravitee-node-tracing/src/main/java/io/gravitee/node/tracing/NoOpSpan.java, gravitee-node-tracing/src/main/java/io/gravitee/node/tracing/TracingService.java, gravitee-node-tracing/src/main/java/io/gravitee/node/tracing/plugin/TracerPlugin.java, gravitee-node-tracing/src/main/java/io/gravitee/node/tracing/plugin/TracingPluginHandler.java, gravitee-node-tracing/src/main/java/io/gravitee/node/tracing/spring/TracingConfiguration.java, gravitee-node-tracing/src/main/java/io/gravitee/node/tracing/vertx/LazyVertxTracer.java, gravitee-node-tracing/src/main/java/io/gravitee/node/tracing/vertx/LazyVertxTracerFactory.java, gravitee-node-tracing/src/main/java/io/gravitee/node/tracing/vertx/VertxTracer.java, gravitee-node-tracing/src/main/resources/META-INF/spring.factories, gravitee-node-vertx/pom.xml, gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java, pom.xml
Closes gravitee-io/issues#1581
=> feat(tracing): Provide initial implementation of Tracing support

gravitee-node-container/src/main/java/io/gravitee/node/container/AbstractNode.java, gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/infos/NodeInfosService.java, gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/monitor/NodeMonitorService.java, gravitee-node-plugins/gravitee-node-plugins-service/src/main/java/io/gravitee/node/plugins/service/impl/ServiceManagerImpl.java, gravitee-node-reporter/src/main/java/io/gravitee/node/reporter/vertx/ReporterManagerImpl.java, pom.xml
Closes gravitee-io/issues#5966
=> fix(event): propagate node stop event when shutdown

gravitee-node-reporter/src/main/java/io/gravitee/node/reporter/vertx/ReporterManagerImpl.java
Closes gravitee-io/issues#5966
=> fix(event): propagate node stop event when shutdown reporters

.circleci/config.yml, gravitee-node-container/src/main/java/io/gravitee/node/container/AbstractNode.java, gravitee-node-plugins/gravitee-node-plugins-service/src/main/java/io/gravitee/node/plugins/service/impl/ServiceManagerImpl.java, gravitee-node-reporter/src/main/java/io/gravitee/node/reporter/vertx/ReporterManagerImpl.java, gravitee-node-services/gravitee-node-services-monitoring/src/main/java/io/gravitee/node/service/monitoring/MonitoringService.java, pom.xml
=> fix: node stop event not well propagated

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java
Closes gravitee-io/issues#6555
=> fix(metrics): properly ignore useless metrics

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/configuration/HttpServerConfiguration.java
Issue: https://github.com/gravitee-io/issues/issues/6568
=> Add possibility to pre-define Vertx HTTP Server host name and port

gravitee-node-container/src/main/java/io/gravitee/node/container/AbstractContainer.java, gravitee-node-container/src/main/java/io/gravitee/node/container/AbstractNode.java, pom.xml
Closes gravitee-io/issues#6722
=> feat(graceful): apply delay before shutdown

gravitee-node-container/src/main/java/io/gravitee/node/container/spring/env/GraviteeEnvironmentPropertySource.java
Closes gravitee-io/issues#6909
=> fix(conf): contains method must also be based on relaxed properties

pom.xml
=> chore: Support for Java 17

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/configuration/HttpServerConfiguration.java
=> fix: bad tls ciphers configuration

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/spring/VertxConfiguration.java
Cherry-pick: https://github.com/gravitee-io/gravitee-node/commit/749993b0b9bd7d7df655306c6fdac9e0031770f8
=> Add missing bean in 1.19.x

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/spring/VertxConfiguration.java
Continue to fix 1.19.x branch...
(cherry picked from commit 749993b)
=> [Backport] Do not call close method multiple times

gravitee-node-api/src/main/java/io/gravitee/node/api/notifier/NotificationAcknowledge.java, gravitee-node-api/src/main/java/io/gravitee/node/api/notifier/NotificationAcknowledgeRepository.java, gravitee-node-api/src/main/java/io/gravitee/node/api/notifier/NotificationCondition.java, gravitee-node-api/src/main/java/io/gravitee/node/api/notifier/NotificationDefinition.java, gravitee-node-api/src/main/java/io/gravitee/node/api/notifier/NotifierService.java, gravitee-node-api/src/main/java/io/gravitee/node/api/notifier/ResendNotificationCondition.java, gravitee-node-notifier/pom.xml, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/NotifierServiceImpl.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/NotifierUtils.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/plugin/NotifierPluginConfigurationFactory.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/plugin/NotifierPluginFactory.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/plugin/NotifierPluginProvider.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/plugin/impl/NotifierPluginConfigurationFactoryImpl.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/plugin/impl/NotifierPluginFactoryImpl.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/spring/NotifierConfiguration.java, gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/trigger/NotificationTrigger.java, gravitee-node-notifier/src/test/java/io/gravitee/node/notifier/trigger/NotificationTriggerTest.java, pom.xml
=> feat: addition of platform notifier mechanism

gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/metrics/Metrics.java
**Issue**
---
- use it directly by updating your project with version: `1.22.0-feat-metrics-registery-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.22.0-feat-metrics-registery-SNAPSHOT/gravitee-node-1.22.0-feat-metrics-registery-SNAPSHOT.zip)
=> feat: provide access to meter registry

gravitee-node-api/src/main/java/io/gravitee/node/api/Node.java, gravitee-node-api/src/main/java/io/gravitee/node/api/license/Feature.java, gravitee-node-api/src/main/java/io/gravitee/node/api/license/License.java, gravitee-node-container/src/main/java/io/gravitee/node/container/AbstractNode.java, gravitee-node-container/src/main/java/io/gravitee/node/container/NodeFactory.java, gravitee-node-container/src/main/java/io/gravitee/node/container/plugin/NodeDeploymentContextFactory.java, gravitee-node-container/src/main/java/io/gravitee/node/container/spring/NodeConfiguration.java, gravitee-node-license/pom.xml, gravitee-node-license/src/main/java/io/gravitee/node/license/LicenseService.java, gravitee-node-license/src/main/java/io/gravitee/node/license/license3j/License3JFeature.java, gravitee-node-license/src/main/java/io/gravitee/node/license/license3j/License3JLicense.java, gravitee-node-license/src/main/java/io/gravitee/node/license/management/NodeLicenseManagementEndpoint.java, gravitee-node-license/src/test/java/io/gravitee/node/license/LicenseTest.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/node/NodeEndpoint.java, pom.xml
**Issue**
---
- use it directly by updating your project with version: `1.22.0`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.22.0/gravitee-node-1.22.0.zip)
=> refactor: Single distribution bundle for CE / EE

gravitee-node-services/gravitee-node-services-initializer/src/main/java/io/gravitee/node/services/initializer/spring/InitializerConfiguration.java, gravitee-node-services/gravitee-node-services-upgrader/src/main/java/io/gravitee/node/services/upgrader/UpgraderServiceImpl.java, gravitee-node-services/gravitee-node-services-upgrader/src/main/java/io/gravitee/node/services/upgrader/spring/UpgraderConfiguration.java
=> fix: get upgrade.mode from env variables

gravitee-node-api/src/main/java/io/gravitee/node/api/upgrader/UpgradeRecord.java
**Issue**
---
- use it directly by updating your project with version: `1.27.2-fix-upgrader-framework-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.27.2-fix-upgrader-framework-SNAPSHOT/gravitee-node-1.27.2-fix-upgrader-framework-SNAPSHOT.zip)
=> fix: add hashcode and equals to UpgraderRecord

gravitee-node-reporter/src/main/java/io/gravitee/node/reporter/vertx/eventbus/EventBusReporterWrapper.java, pom.xml
=> fix: bump reporter api version

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java
**Issue**
https://github.com/gravitee-io/issues/issues/8927
https://gravitee.atlassian.net/browse/APIM-1047
Make sure the VertxFactory doesn't try to list all environment properties by using `environment.getProperty("xxx")` instead of `EnvironmentUtils.getPropertiesStartingWith("xxxx")`.
`KubernetesPropertyResolver` needs a `KubernetesClient` which needs a vertx instance. Vertx instance is instantiated with `VertxFactory` which, when a particular configuration is enabled (`service.metrics.enabled`), tries to customize the metrics labels by looking at the configuration. When doing that, it calls `EnvironmentUtils.getPropertiesStartingWith("xxxxxx")` which basically iterates over all the spring property resolvers including  `KubernetesPropertyResolver` -> :boom:
The fix …
=> fix: avoid spring loading issue with vertx and k8s client

gravitee-node-certificates/pom.xml, gravitee-node-cluster/pom.xml, gravitee-node-container/pom.xml, gravitee-node-kubernetes/pom.xml, gravitee-node-license/pom.xml, gravitee-node-management/pom.xml, gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/NodeMonitoringServiceTest.java, gravitee-node-plugins/pom.xml, gravitee-node-reporter/pom.xml, pom.xml
**Issue**
---
- use it directly by updating your project with version: `3.0.0-upgrade-deps-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/3.0.0-upgrade-deps-SNAPSHOT/gravitee-node-3.0.0-upgrade-deps-SNAPSHOT.zip)
=> fix(deps): upgrade gravitee-bom, gravitee-common & reporter-api

pom.xml
Just update the internal reference
=> chore: update internal dependencies reference

gravitee-node-license/src/main/java/io/gravitee/node/license/LicenseService.java, pom.xml
see https://gravitee.atlassian.net/browse/APIM-343 
see https://github.com/gravitee-io/issues/issues/8659
---
- use it directly by updating your project with version: `1.24.8-fix-mongo-upgrader-1-24-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.24.8-fix-mongo-upgrader-1-24-x-SNAPSHOT/gravitee-node-1.24.8-fix-mongo-upgrader-1-24-x-SNAPSHOT.zip)
=> [1.24.x] fix: license error in community mode

gravitee-node-license/src/main/java/io/gravitee/node/license/LicenseService.java, pom.xml
see https://gravitee.atlassian.net/browse/APIM-343 
see https://github.com/gravitee-io/issues/issues/8659
---
- use it directly by updating your project with version: `1.25.7-fix-mongo-upgrader-1-25-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.25.7-fix-mongo-upgrader-1-25-x-SNAPSHOT/gravitee-node-1.25.7-fix-mongo-upgrader-1-25-x-SNAPSHOT.zip)
=> [1.25.x] fix: license error in community mode

gravitee-node-license/src/main/java/io/gravitee/node/license/LicenseService.java, pom.xml
see https://gravitee.atlassian.net/browse/APIM-343 
see https://github.com/gravitee-io/issues/issues/8659
---
- use it directly by updating your project with version: `1.27.9-fix-mongo-upgrader-1-27-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.27.9-fix-mongo-upgrader-1-27-x-SNAPSHOT/gravitee-node-1.27.9-fix-mongo-upgrader-1-27-x-SNAPSHOT.zip)
=> [1.27.x] fix: license error in community mode

gravitee-node-license/src/main/java/io/gravitee/node/license/LicenseService.java, pom.xml
see https://gravitee.atlassian.net/browse/APIM-343
see https://github.com/gravitee-io/issues/issues/8659
---
- use it directly by updating your project with version: `2.0.8-fix-license-errors-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/2.0.8-fix-license-errors-SNAPSHOT/gravitee-node-2.0.8-fix-license-errors-SNAPSHOT.zip)
=> [2.0.x] fix: license error in community mode

README.adoc, gravitee-node-cache/README.adoc, gravitee-node-cluster/README.adoc
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-241
- add global README to explain modules and release
- add cache and cluster README to explain how it works
---
- use it directly by updating your project with version: `3.1.0-archi-241-add-doc-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/3.1.0-archi-241-add-doc-SNAPSHOT/gravitee-node-3.1.0-archi-241-add-doc-SNAPSHOT.zip)
=> doc: add README

gravitee-node-license/src/main/resources/license-model.yml, gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java
see https://gravitee.atlassian.net/browse/APIM-1685
---
- use it directly by updating your project with version: `4.0.0-feat-add-transform-avro-json-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.0.0-feat-add-transform-avro-json-SNAPSHOT/gravitee-node-4.0.0-feat-add-transform-avro-json-SNAPSHOT.zip)
=> feat: add transform avro json

pom.xml
**Issue**
https://gravitee.atlassian.net/browse/archi-222
update kubernetes client to version 3.0.0
=> Archi 222 update k8s client

gravitee-node-license/src/main/resources/license-model.yml, gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java
**Issue**
---
- use it directly by updating your project with version: `4.4.0-archi-222-clean-up-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.4.0-archi-222-clean-up-SNAPSHOT/gravitee-node-4.4.0-archi-222-clean-up-SNAPSHOT.zip)
=> Archi 222 clean up

gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/HazelcastClusterManager.java
In order to keep track of added listener, a local hash map is used to avoid recreating multi time the same queue.
---
- use it directly by updating your project with version: `4.7.1-fix-hazelcast-queue-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.7.1-fix-hazelcast-queue-SNAPSHOT/gravitee-node-4.7.1-fix-hazelcast-queue-SNAPSHOT.zip)
=> fix: use local hash map to keep reference to created queue

gravitee-node-license/src/main/resources/license-model.yml
**Issue**
https://gravitee.atlassian.net/browse/TT-3493
Create an OEM pack that includes customization feature
---
- use it directly by updating your project with version: `5.0.1-TT-3493-oem-pack-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.0.1-TT-3493-oem-pack-SNAPSHOT/gravitee-node-5.0.1-TT-3493-oem-pack-SNAPSHOT.zip)
=> fix: add oem pack

gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/pom.xml, gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/test/java/io/gravitee/node/plugin/cluster/hazelcast/HazelcastClusterManagerTest.java, gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/test/resources/cluster.xml, gravitee-node-jetty/pom.xml, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/JettyHttpServer.java, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/JettyHttpServerFactory.java, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/handler/NoContentOutputErrorHandler.java, gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/spring/JettyContainerConfiguration.java, gravitee-node-kubernetes/src/main/java/io/gravitee/node/kubernetes/spring/NodeKubernetesConfiguration.java, gravitee-node-secrets/gravitee-node-secrets-service/src/main/java/io/gravitee/node/secrets/service/spring/SecretServiceConfiguration.java, pom.xml
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-296
update and fix following bom upgrade
---
- use it directly by updating your project with version: `5.4.0-archi-296-upgrade-bom-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.4.0-archi-296-upgrade-bom-SNAPSHOT/gravitee-node-5.4.0-archi-296-upgrade-bom-SNAPSHOT.zip)
=> Archi 296 upgrade bom

gravitee-node-license/src/main/resources/license-model.yml, gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java
see https://gravitee.atlassian.net/browse/APIM-657
see https://gravitee.atlassian.net/browse/APIM-657
---
- use it directly by updating your project with version: `5.5.0-feat-transform-protobuf-json-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.5.0-feat-transform-protobuf-json-SNAPSHOT/gravitee-node-5.5.0-feat-transform-protobuf-json-SNAPSHOT.zip)
=> feat: add protobuf to json transform to license features

gravitee-node-license/src/main/resources/license-model.yml, gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java
---
- use it directly by updating your project with version: `4.9.0-feat-transform-protobuf-avro-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.9.0-feat-transform-protobuf-avro-SNAPSHOT/gravitee-node-4.9.0-feat-transform-protobuf-avro-SNAPSHOT.zip)
=> feat: add protobuf-json and avro-protobuf features

gravitee-node-license/src/main/resources/license-model.yml, gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java
Fixes: AM-3077
---
- use it directly by updating your project with version: `5.14.0-AM-3077-orange-plugin-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.14.0-AM-3077-orange-plugin-SNAPSHOT/gravitee-node-5.14.0-AM-3077-orange-plugin-SNAPSHOT.zip)
=> feat: add orange contact everyone plugin

gravitee-node-license/src/main/resources/license-model.yml, gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java
=> fix: add orange contact everyone plugin

gravitee-node-container/src/main/java/io/gravitee/node/container/spring/env/AbstractGraviteePropertySource.java
fixes AM-3317
**Issue**
https://gravitee.atlassian.net/browse/AM-3317
---
- use it directly by updating your project with version: `5.14.8-AM-3317-fix-stackoverflow-ex-on-watch-loop-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.14.8-AM-3317-fix-stackoverflow-ex-on-watch-loop-SNAPSHOT/gravitee-node-5.14.8-AM-3317-fix-stackoverflow-ex-on-watch-loop-SNAPSHOT.zip)
=> fix: recursive method leads to stack overflow exception.

gravitee-node-certificates/src/main/java/io/gravitee/node/certificates/x509/RefreshableX509TrustManagerDelegator.java, gravitee-node-certificates/src/test/java/io/gravitee/node/certificates/x509/RefreshableX509TrustManagerDelegatorTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-6628
Backport
=> fix: return empty array of accepted issuers in trust manager

gravitee-node-license/src/main/resources/license-model.yml, gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-4334
https://gravitee.atlassian.net/browse/APIM-4334?focusedCommentId=37017
Add a feature for data cache policy
---
- use it directly by updating your project with version: `6.6.0-apim-4334-add-data-cache-policy-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.6.0-apim-4334-add-data-cache-policy-SNAPSHOT/gravitee-node-6.6.0-apim-4334-add-data-cache-policy-SNAPSHOT.zip)
=> feat: add data cache policy

gravitee-node-api/src/main/java/io/gravitee/node/api/secrets/model/Secret.java, gravitee-node-api/src/main/java/io/gravitee/node/api/secrets/model/SecretMap.java, gravitee-node-api/src/main/java/io/gravitee/node/api/secrets/model/SecretURL.java, gravitee-node-api/src/main/java/io/gravitee/node/api/secrets/model/WithExpiration.java, gravitee-node-api/src/test/java/io/gravitee/node/api/secrets/model/SecretMapTest.java, gravitee-node-api/src/test/java/io/gravitee/node/api/secrets/model/SecretURLTest.java, gravitee-node-license/src/main/resources/license-model.yml, gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java, gravitee-node-secrets/gravitee-secret-provider-mock/pom.xml, gravitee-node-secrets/gravitee-secret-provider-mock/src/main/assembly/plugin-assembly.xml, gravitee-node-secrets/gravitee-secret-provider-mock/src/main/java/io/gravitee/node/secrets/plugin/mock/MockSecretLocation.java, gravitee-node-secrets/gravitee-secret-provider-mock/src/main/java/io/gravitee/node/secrets/plugin/mock/MockSecretProvider.java, gravitee-node-secrets/gravitee-secret-provider-mock/src/main/java/io/gravitee/node/secrets/plugin/mock/MockSecretProviderException.java, gravitee-node-secrets/gravitee-secret-provider-mock/src/main/java/io/gravitee/node/secrets/plugin/mock/MockSecretProviderFactory.java, gravitee-node-secrets/gravitee-secret-provider-mock/src/main/java/io/gravitee/node/secrets/plugin/mock/conf/ConfiguredError.java, gravitee-node-secrets/gravitee-secret-provider-mock/src/main/java/io/gravitee/node/secrets/plugin/mock/conf/ConfiguredEvent.java, gravitee-node-secrets/gravitee-secret-provider-mock/src/main/java/io/gravitee/node/secrets/plugin/mock/conf/MockSecretProviderConfiguration.java, gravitee-node-secrets/gravitee-secret-provider-mock/src/main/java/io/gravitee/node/secrets/plugin/mock/conf/Renewal.java, gravitee-node-secrets/gravitee-secret-provider-mock/src/main/resources/plugin.properties, gravitee-node-secrets/gravitee-secret-provider-mock/src/test/java/io/gravitee/node/secrets/plugin/mock/MockSecretProviderTest.java, gravitee-node-secrets/pom.xml, pom.xml
**Issue**
APIM-7412
* Update of Secret/SecretMap/SecretURL that will trigger a BC in secret-providers
* Draft version of mock secret provider
---
- use it directly by updating your project with version: `7.0.0-APIM-7412-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.0.0-APIM-7412-SNAPSHOT/gravitee-node-7.0.0-APIM-7412-SNAPSHOT.zip)
=> feat: service secrets common objects and interfaces

gravitee-node-secrets/gravitee-node-secrets-config/src/main/java/io/gravitee/node/secrets/config/GraviteeConfigurationSecretResolver.java
fix: configuration secrets cache
---
- use it directly by updating your project with version: `7.0.1-fix-flaky-k8s-it-tests-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.0.1-fix-flaky-k8s-it-tests-SNAPSHOT/gravitee-node-7.0.1-fix-flaky-k8s-it-tests-SNAPSHOT.zip)
=> fix: configuration secrets cache

pom.xml
**Issue**
https://gravitee.atlassian.net/browse/APIM-6541
---
- use it directly by updating your project with version: `7.0.3-APIM-6541-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.0.3-APIM-6541-SNAPSHOT/gravitee-node-7.0.3-APIM-6541-SNAPSHOT.zip)
=> fix: update kubernetes client version

gravitee-node-opentelemetry/README.adoc, gravitee-node-opentelemetry/src/main/java/io/gravitee/node/opentelemetry/configuration/OpenTelemetryConfiguration.java, gravitee-node-opentelemetry/src/test/java/io/gravitee/node/opentelemetry/configuration/OpenTelemetryConfigurationTest.java
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-481
* Fixed configuration read errors on map and list
* Fixed README
---
- use it directly by updating your project with version: `7.0.6-ARCHI-481-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.0.6-ARCHI-481-SNAPSHOT/gravitee-node-7.0.6-ARCHI-481-SNAPSHOT.zip)
=> fix: opentelemetry configuration and README

gravitee-node-opentelemetry/README.adoc, gravitee-node-opentelemetry/src/main/java/io/gravitee/node/opentelemetry/configuration/OpenTelemetryConfiguration.java, gravitee-node-opentelemetry/src/test/java/io/gravitee/node/opentelemetry/configuration/OpenTelemetryConfigurationTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-8722
Backward compatibility break fix
---
- use it directly by updating your project with version: `7.0.7-ARCHI-481-reg-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.0.7-ARCHI-481-reg-SNAPSHOT/gravitee-node-7.0.7-ARCHI-481-reg-SNAPSHOT.zip)
=> fix: backward compatibility fix

gravitee-node-license/src/main/resources/license-model.yml
**Issue**
https://gravitee.atlassian.net/browse/APIM-9299
Add new pack `ai-gateway` 
---
- use it directly by updating your project with version: `7.5.0-apim9299-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.5.0-apim9299-SNAPSHOT/gravitee-node-7.5.0-apim9299-SNAPSHOT.zip)
=> feat: add new "ai-gateway" pack

pom.xml
APIM-8986
**Issue**
---
- use it directly by updating your project with version: `7.6.0-apim-8986-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.6.0-apim-8986-SNAPSHOT/gravitee-node-7.6.0-apim-8986-SNAPSHOT.zip)
=> feat: handle double additional metrics

gravitee-node-management/src/main/java/io/gravitee/node/management/http/metrics/prometheus/PrometheusEndpoint.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/utils/ConcurrencyLimitHandler.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/utils/OffloadHandler.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/utils/SafeBufferedWriter.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/verticle/ManagementVerticle.java, gravitee-node-management/src/test/java/io/gravitee/node/management/http/utils/ConcurrencyLimitHandlerTest.java, gravitee-node-management/src/test/java/io/gravitee/node/management/http/utils/OffloadHandlerTest.java, gravitee-node-management/src/test/java/io/gravitee/node/management/http/utils/SafeBufferedWriterTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-9423
cherry-picked from https://github.com/gravitee-io/gravitee-node/pull/426
---
- use it directly by updating your project with version: `7.11.2-APIM-9254-changes-for-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.11.2-APIM-9254-changes-for-master-SNAPSHOT/gravitee-node-7.11.2-APIM-9254-changes-for-master-SNAPSHOT.zip)
=> fix: Prometheus OOM error

gravitee-node-management/src/main/java/io/gravitee/node/management/http/metrics/prometheus/PrometheusEndpoint.java, gravitee-node-management/src/main/java/io/gravitee/node/management/http/utils/OffloadHandler.java
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-9254
https://github.com/user-attachments/assets/3530627c-9ba4-4722-b161-f262bf8b9403
---
- use it directly by updating your project with version: `6.8.4-apim-9254-request-Not-Terminating-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.8.4-apim-9254-request-Not-Terminating-SNAPSHOT/gravitee-node-6.8.4-apim-9254-request-Not-Terminating-SNAPSHOT.zip)
=> fix: prometheus endpoint non responsive
