gravitee-node-vertx/pom.xml
pom.xml

Closes gravitee-io/issues#5996

chore: Add dependency to LatencyUtils as it's required by micrometer

---

gravitee-node-plugins/gravitee-node-plugins-service/src/main/java/io/gravitee/node/plugins/service/impl/ServiceManagerImpl.java
gravitee-node-plugins/gravitee-node-plugins-service/src/test/java/io/gravitee/node/plugins/service/impl/ServiceManagerImplTest.java
gravitee-node-plugins/pom.xml
pom.xml

https://github.com/gravitee-io/issues/issues/6306
fix: ServiceManager takes care of AbstractService.getOrder() to start services
ServiceManager starts all services plugins using this order, starting with lower ones at first.
And stops them starting with higher ones at first.
It avoids that services consuming SyncService DEPLOY events starts after it.

fix: ServiceManager takes care of AbstractService.getOrder() to start services

---

gravitee-node-container/src/main/java/io/gravitee/node/container/spring/env/AbstractGraviteePropertySource.java

In gravitee-common's EnvironmentUtils class, we have a getAllProperties that should return all properties of an environment.
Because Gravitee's property source was not enumerable nor composite, the helper function was not returning gravitee properties.
See https://github.com/gravitee-io/gravitee-common/blob/master/src/main/java/io/gravitee/common/util/EnvironmentUtils.java#L69
It will fix the [Cockpit initial plans](https://github.com/gravitee-io/gravitee-cockpit/blob/master/gravitee-cockpit-service/src/main/java/com/graviteesource/cockpit/service/spring/InitialPlansConfiguration.java#L21) loading where getting all environment properties were not returning properties from gravitee source and we will be able to update `gravitee-node` …

Feat make gravitee property source enumerable [1.18.x]

---

gravitee-node-container/src/main/java/io/gravitee/node/container/spring/env/AbstractGraviteePropertySource.java

In gravitee-common's EnvironmentUtils class, we have a getAllProperties that should return all properties of an environment.
Because Gravitee's property source was not enumerable nor composite, the helper function was not returning gravitee properties.
See https://github.com/gravitee-io/gravitee-common/blob/master/src/main/java/io/gravitee/common/util/EnvironmentUtils.java#L69
It will fix the [Cockpit initial plans](https://github.com/gravitee-io/gravitee-cockpit/blob/master/gravitee-cockpit-service/src/main/java/com/graviteesource/cockpit/service/spring/InitialPlansConfiguration.java#L21) loading where getting all environment properties were not returning properties from gravitee source and we will be able to update `gravitee-node` …

feat: make gravitee propertysource enumerable

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java

Add support for old prometheus label names for backward compatibility

---

gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/micrometer/NodeHealthCheckMicrometerHandler.java

gravitee-io/issues#6924
When initializing the gauge for node health probes, we didn't use the same object as when the probes are updated.
By using the same `entry`, the gauge will register the right object.

fix health probes updating

---

gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/infos/NodeInfosService.java

When the node were stopping during the license check, we were having a NPE on the `nodeInfos`.
Our hypothesis is that as the node didn't complete the startup process, the `nodeInfos` has never been initialized. Therefore, a simple null check should be enough.
Ex:
```
09:43:44.455 [main] ERROR c.g.l.node.service.LicenseService - License is expired. Please contact GraviteeSource to ask for a renewed license.
09:43:44.456 [main] INFO  c.g.l.n.deployer.WrappedLicensedNode - Gravitee.io - Cockpit Management API is stopping
09:43:44.461 [main] ERROR c.g.l.n.deployer.WrappedLicensedNode - An error occurred while pre-stopping component NodeInfosService
java.lang.NullPointerException: Cannot invoke "io.gravitee.node.api.infos.NodeInfos.setStatus(io.gravitee.node.api.infos.NodeStatus)" because …
```

fix: npe when stopping due to license invalid

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/configuration/HttpServerConfiguration.java

When creating an `HttpServerConfiguration`, it is impossible to define a default value for the field `clientAuth`.
The one defined via the method `withDefaultClientAuth` is ignored when building the final object.

fix(vertx-node): make use of the default clientAuth in HttpServer configuration

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/configuration/HttpServerConfiguration.java

When creating an `HttpServerConfiguration`, it is impossible to define default values for the fields `clientAuth`, `keyStoreKubernetes` and `trustStorePaths `.
The ones defined via the method `withDefault<fieldName>` are ignored when building the final object.

[1.20.x] fix http server config defaults

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/configuration/HttpServerConfiguration.java

Similar to https://github.com/gravitee-io/gravitee-node/pull/131, default values are ignored for `HttpServerConfiguration` properties `keyStoreKubernetes` and `trustStorePaths`

fix(vertx-node): use default values for array HttpServerConfiguraiton properties

---

gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/JettyHttpConfiguration.java
gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/JettyHttpServerFactory.java

**Issue**
https://github.com/gravitee-io/issues/issues/7479
Added 
```
HttpConfiguration httpConfig = new HttpConfiguration();
httpConfig.setOutputBufferSize(32768);
httpConfig.setRequestHeaderSize(8192);
httpConfig.setResponseHeaderSize(8192);
```
as part of the configuration for jetty
[Helm charts
](https://github.com/gravitee-io/helm-charts/pull/238)
---
- use it directly by updating your project with version: `1.21.1-issues-7479-hardcoded-buffer-header-size-options-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravite …

fix: configurable jetty http  header and buffer size

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/AbstractVertxHttpServerFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/configuration/HttpServerConfiguration.java

**Issue**
If the websocket is used to transfer video streams, the default frame size / message size is too small which throws an exception.
Max frame length of 65536 has been exceeded
Extend websocket frame size and message size in configuration.
Configuration:
http.websocket.maxWebSocketFrameSize
http.websocket.maxWebSocketMessageSize

extend websocket config: frame , message size

---

gravitee-node-kubernetes/src/main/java/io/gravitee/node/kubernetes/keystoreloader/AbstractKubernetesKeyStoreLoader.java
gravitee-node-kubernetes/src/main/java/io/gravitee/node/kubernetes/keystoreloader/KubernetesConfigMapKeyStoreLoader.java
gravitee-node-kubernetes/src/main/java/io/gravitee/node/kubernetes/keystoreloader/KubernetesKeyStoreLoaderFactory.java
gravitee-node-kubernetes/src/main/java/io/gravitee/node/kubernetes/keystoreloader/KubernetesSecretKeyStoreLoader.java
gravitee-node-kubernetes/src/main/java/io/gravitee/node/kubernetes/propertyresolver/KubernetesPropertyResolver.java
gravitee-node-kubernetes/src/test/java/io/gravitee/node/kubernetes/keystoreloader/KubernetesConfigMapKeyStoreLoaderTest.java
gravitee-node-kubernetes/src/test/java/io/gravitee/node/kubernetes/keystoreloader/KubernetesSecretKeyStoreLoaderTest.java
pom.xml

---
- use it directly by updating your project with version: `1.23.0-7019-k8s-client-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.23.0-7019-k8s-client-SNAPSHOT/gravitee-node-1.23.0-7019-k8s-client-SNAPSHOT.zip)

feat: Use the new Kubernetes Client API

---

gravitee-node-api/src/main/java/io/gravitee/node/api/deployer/AbstractPluginDeploymentLifecycle.java

---
- use it directly by updating your project with version: `1.24.1-fix-provide-default-license-validation-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.24.1-fix-provide-default-license-validation-SNAPSHOT/gravitee-node-1.24.1-fix-provide-default-license-validation-SNAPSHOT.zip)

fix: implement abtract plugin deployment to validate license feature

---

gravitee-node-api/pom.xml
gravitee-node-cache/pom.xml
gravitee-node-certificates/pom.xml
gravitee-node-cluster/pom.xml
gravitee-node-container/pom.xml
gravitee-node-jetty/pom.xml
gravitee-node-kubernetes/pom.xml
gravitee-node-license/pom.xml
gravitee-node-management/pom.xml
gravitee-node-monitoring/pom.xml
gravitee-node-notifier/pom.xml
gravitee-node-plugins/gravitee-node-plugins-service/pom.xml
gravitee-node-plugins/pom.xml
gravitee-node-reporter/pom.xml
gravitee-node-tracing/pom.xml
gravitee-node-vertx/pom.xml
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/metrics/ExcludeTagsFilter.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/metrics/RenameVertxFilter.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/VertxFactoryTest.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/metrics/ExcludeTagsFilterTest.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/metrics/RenameVertxFilterTest.java
gravitee-node-vertx/src/test/resources/logback-test.xml
pom.xml

**Issue**
https://github.com/gravitee-io/issues/issues/8218
With that PR it is now possible to include or exclude a metric labels (aka tags) for a specific domain (aka category) by specifying it in the configuration.
By default, the following labels are included:
- `local`
- `http_method`
- `http_code`
On the apim gateway, if you want to include the tag `remote` only for the `http.client` (and avoid adding it for other categories, especially http.server), you can specify the following configuration: `gravitee.services.metrics.include.http.client[0]=remote`
You can also try to exclude the tag `local` on the `http.client` category because it is useless (vertx always set the value to '?'), you can add the following configuration: …

feat: allows to include or exclude metrics labels

---

gravitee-node-cluster/src/main/java/io/gravitee/node/cluster/spring/HazelcastClusterConfiguration.java

Supporting Yaml configuration file should ease the overriding config in Helm chart. Currently, with the XML file, we can't use Helm/Go template function to merge properties.
With the YAML, we should be able to define a default configuration in the Helm chart and, let users overrides part of that configuration with values, using https://rm3l.org/merging-dynamic-config-data-in-helm-charts/
---
- use it directly by updating your project with version: `1.26.0-hazelcast-support-yaml-config-file-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee- …

feat: support yaml file for Hazelcast configuration

---

pom.xml

**Issue**
---
- use it directly by updating your project with version: `1.26.1-kube-client-upgrade-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.26.1-kube-client-upgrade-SNAPSHOT/gravitee-node-1.26.1-kube-client-upgrade-SNAPSHOT.zip)

fix: Upgrade dependency to gravitee-kubernetes

---

gravitee-node-api/src/main/java/io/gravitee/node/api/initializer/Initializer.java
gravitee-node-api/src/main/java/io/gravitee/node/api/upgrader/UpgradeRecord.java
gravitee-node-api/src/main/java/io/gravitee/node/api/upgrader/Upgrader.java
gravitee-node-api/src/main/java/io/gravitee/node/api/upgrader/UpgraderRepository.java
gravitee-node-services/gravitee-node-services-initializer/pom.xml
gravitee-node-services/gravitee-node-services-initializer/src/main/java/io/gravitee/node/services/initializer/InitializerServiceImpl.java
gravitee-node-services/gravitee-node-services-initializer/src/main/java/io/gravitee/node/services/initializer/spring/InitializerConfiguration.java
gravitee-node-services/gravitee-node-services-initializer/src/test/java/io/gravitee/node/services/initializer/InitializerServiceImplTest.java
gravitee-node-services/gravitee-node-services-upgrader/pom.xml
gravitee-node-services/gravitee-node-services-upgrader/src/main/java/io/gravitee/node/services/upgrader/UpgraderServiceImpl.java
gravitee-node-services/gravitee-node-services-upgrader/src/main/java/io/gravitee/node/services/upgrader/spring/UpgraderConfiguration.java
gravitee-node-services/gravitee-node-services-upgrader/src/test/java/io/gravitee/node/services/upgrader/UpgraderServiceImplTest.java
gravitee-node-services/pom.xml
pom.xml

https://graviteedevops.atlassian.net/browse/ARCHI-71
---
- use it directly by updating your project with version: `1.27.0-ARCH-71-Upgrader-Framework-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.27.0-ARCH-71-Upgrader-Framework-SNAPSHOT/gravitee-node-1.27.0-ARCH-71-Upgrader-Framework-SNAPSHOT.zip)

Implement upgrader framework

---

gravitee-node-cache/pom.xml

**Issue**
NA
Using provided dep means every user of this lib will need to add the dep in his own pom.xml, however, it looks like we are regularly missing that, causing some troubles. As per previous discussion, we want to restrict the usage of provided deps to plugins.
---
- use it directly by updating your project with version: `1.27.3-guava-compile-scope-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.27.3-guava-compile-scope-SNAPSHOT/gravitee-node-1.27.3-guava-compile-scope-SNAPSHOT.zip)

fix(node-cache): move guava to compile scope instead of provided

---

gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/monitor/NodeMonitorManagementEndpoint.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-616
For `/_node/monitor`, we tried to set status code after writing the response, but the head was already sent, causing an error
---
- use it directly by updating your project with version: `1.24.4-support-616-internal-monitor-apim-3-18-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.24.4-support-616-internal-monitor-apim-3-18-SNAPSHOT/gravitee-node-1.24.4-support-616-internal-monitor-apim-3-18-SNAPSHOT.zip)

fix(api): send head before writing response for /monitor

---

gravitee-node-management/src/main/java/io/gravitee/node/management/http/configuration/ConfigurationEndpoint.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-781
Load `graviteeYamlConfiguration` property source instead of the old `graviteeConfiguration`
---
- use it directly by updating your project with version: `1.24.5-support-781-internal-configuration-apim-3-18-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.24.5-support-781-internal-configuration-apim-3-18-SNAPSHOT/gravitee-node-1.24.5-support-781-internal-configuration-apim-3-18-SNAPSHOT.zip)

fix(api): load the right property source for /configuration

---

gravitee-node-certificates/src/test/java/io/gravitee/node/certificates/ReloadableKeyManagerTest.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/cert/VertxCertificateManager.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/cert/VertxKeyCertOptions.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/cert/VertxKeyManagerFactory.java
pom.xml

**Issue**
N/A
Upgrade to the latest bom v4 that includes the latest vertx version.
This includes a fix discovered with vertx 4.3.8 when we enable TLS on the apim gateway.
---
- use it directly by updating your project with version: `3.0.0-update-vertx-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/3.0.0-update-vertx-SNAPSHOT/gravitee-node-3.0.0-update-vertx-SNAPSHOT.zip)

feat: move to bom v4 and vertx 4.3.8

---

pom.xml

---
- use it directly by updating your project with version: `2.0.4-fix-update-dependency-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/2.0.4-fix-update-dependency-SNAPSHOT/gravitee-node-2.0.4-fix-update-dependency-SNAPSHOT.zip)

fix: update kubernetes client dependency

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/VertxFactory.java

**Issue**
Backport of https://github.com/gravitee-io/gravitee-node/pull/186
https://github.com/gravitee-io/issues/issues/8927
https://gravitee.atlassian.net/browse/APIM-1047
Make sure the VertxFactory doesn't try to list all environment properties by using `environment.getProperty("xxx")` instead of `EnvironmentUtils.getPropertiesStartingWith("xxxx")`.
`KubernetesPropertyResolver` needs a `KubernetesClient` which needs a vertx instance. Vertx instance is instantiated with `VertxFactory` which, when a particular configuration is enabled (`service.metrics.enabled`), tries to customize the metrics labels by looking at the configuration. When doing that, it calls `EnvironmentUtils.getPropertiesStartingWith("xxxxxx")` which basically iterates over all the spring property …

Backport fix: avoid spring loading issue with vertx and k8s client

---

gravitee-node-license/pom.xml
gravitee-node-license/src/main/java/io/gravitee/node/license/LicenseService.java

**Issue**
https://gravitee.atlassian.net/browse/AM-506
This PR removes the logging level default of License
---
- use it directly by updating your project with version: `1.27.6-AM-506-license-logging-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.27.6-AM-506-license-logging-SNAPSHOT/gravitee-node-1.27.6-AM-506-license-logging-SNAPSHOT.zip)

fix: remove enforced INFO level for license

---

pom.xml

This PR bumps dependencies for:
- Hazelcast (CVE-2022-36437)
- SnakeYML (CVE-2022-38749)
---
- use it directly by updating your project with version: `3.0.0-fix-depedency-bumps-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/3.0.0-fix-depedency-bumps-SNAPSHOT/gravitee-node-3.0.0-fix-depedency-bumps-SNAPSHOT.zip)

fix: bump hazelcast and snake yml dependencies

---

pom.xml

I removed the property but forgot to remove the dependency management entry and maven didn't complain 😢 
---
- use it directly by updating your project with version: `3.0.1-remove-useless-dependency-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/3.0.1-remove-useless-dependency-SNAPSHOT/gravitee-node-3.0.1-remove-useless-dependency-SNAPSHOT.zip)

fix(deps): remove unused gravitee-el dependency

---

gravitee-node-api/src/main/java/io/gravitee/node/api/upgrader/Upgrader.java
gravitee-node-services/gravitee-node-services-upgrader/src/main/java/io/gravitee/node/services/upgrader/UpgraderServiceImpl.java
gravitee-node-services/gravitee-node-services-upgrader/src/test/java/io/gravitee/node/services/upgrader/UpgraderServiceImplTest.java

---
- use it directly by updating your project with version: `3.0.2-fix-dry-run-upgraders-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/3.0.2-fix-dry-run-upgraders-SNAPSHOT/gravitee-node-3.0.2-fix-dry-run-upgraders-SNAPSHOT.zip)

fix: handle dry runs in upgraders

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/configuration/HttpServerConfiguration.java
pom.xml

**Issue**
https://gravitee.atlassian.net/browse/APIM-1381
HttpServerConfiguration builder implementation was only relying on Environment so set default values.
Add lombok's `@With` to be able to set fields after builds with an immutable object.
---
- use it directly by updating your project with version: `1.24.6-apim-1381-debugmode-secured-3-18-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.24.6-apim-1381-debugmode-secured-3-18-SNAPSHOT/gravitee-node-1.24.6-apim-1381-debugmode-secured-3-18-SNAPSHOT.zip)

fix: add 'With' methods to HttpServerConfiguration

---

pom.xml

The upgrade is trying to bring latest fixes of kubernetes client into garvitee-node
---
- use it directly by updating your project with version: `1.25.4-fix-kuberetes-client-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.25.4-fix-kuberetes-client-SNAPSHOT/gravitee-node-1.25.4-fix-kuberetes-client-SNAPSHOT.zip)

fix: bump kubernetes client

---

gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/trigger/NotificationTrigger.java
gravitee-node-notifier/src/test/java/io/gravitee/node/notifier/trigger/NotificationTriggerTest.java
pom.xml

**Issue**
https://gravitee.atlassian.net/browse/COC-223
This PR prevents the `scheduleNextAttempt` step to happen is the NotificationTrigger is already closed with a `started` flag.
When calling `NotifierService.unregister` and subsequently `NotifierService.stopAndRemoveTrigger`, the `NotificationTrigger` can be in its `handle` phase. 
If we call `NotificationTrigger.stop` at the same time, a new timer will be created and there is no possibility of stopping the timer ever again due to the loss of reference of this trigger in the `NotifierService`.
This also creates a memory leak and a loss of performance since the `NotificationTrigger` keeps looping over until the node is restarted
---
🚀 A prerelease version of …

fix: prevent scheduleNextAttempt to happen if trigger is stopped

---

gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/HazelcastClusterManager.java

---
- use it directly by updating your project with version: `3.1.0-fix-use-simple-hazelcast-topic-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/3.1.0-fix-use-simple-hazelcast-topic-SNAPSHOT/gravitee-node-3.1.0-fix-use-simple-hazelcast-topic-SNAPSHOT.zip)

Fix use simple hazelcast topic

---

pom.xml

see https://github.com/gravitee-io/gravitee-kubernetes/pull/54
---
- use it directly by updating your project with version: `3.1.0-fix-kubernetes-client-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/3.1.0-fix-kubernetes-client-version-SNAPSHOT/gravitee-node-3.1.0-fix-kubernetes-client-version-SNAPSHOT.zip)

[alpha] fix: bump gravitee-kubernetes version to 2.0.2

---

gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/monitor/NodeMonitorThread.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-1566
Avoid NPE if CPU load average is null (which can happen on Windows)
---
- use it directly by updating your project with version: `1.24.9-apim1566-npe-in-monitoring-1-24-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.24.9-apim1566-npe-in-monitoring-1-24-SNAPSHOT/gravitee-node-1.24.9-apim1566-npe-in-monitoring-1-24-SNAPSHOT.zip)

fix: avoid npe when evaluating cpu load average

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/AbstractVertxHttpServerFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/configuration/HttpServerConfiguration.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-305
https://github.com/gravitee-io/issues/issues/8644
Apply https://github.com/gravitee-io/gravitee-node/pull/226 on `1.25.x`
---
- use it directly by updating your project with version: `1.25.8-APIM-305-add-keystore-watcher-flag-1-25-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.25.8-APIM-305-add-keystore-watcher-flag-1-25-x-SNAPSHOT/gravitee-node-1.25.8-APIM-305-add-keystore-watcher-flag-1-25-x-SNAPSHOT.zip)

[1.25.x] Add config to disable keystore watcher

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/AbstractVertxHttpServerFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/configuration/HttpServerConfiguration.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-305
https://github.com/gravitee-io/issues/issues/8644
Apply https://github.com/gravitee-io/gravitee-node/pull/226 on `2.0.x`
---
- use it directly by updating your project with version: `2.0.9-APIM-305-add-keystore-watcher-flag-2-0-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/2.0.9-APIM-305-add-keystore-watcher-flag-2-0-x-SNAPSHOT/gravitee-node-2.0.9-APIM-305-add-keystore-watcher-flag-2-0-x-SNAPSHOT.zip)

[2.0.x] Add config to disable keystore watcher

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/AbstractVertxHttpServerFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/configuration/HttpServerConfiguration.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-305
https://github.com/gravitee-io/issues/issues/8644
Apply https://github.com/gravitee-io/gravitee-node/pull/226 on `master`
---
- use it directly by updating your project with version: `3.0.8-APIM-305-add-keystore-watcher-flag-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/3.0.8-APIM-305-add-keystore-watcher-flag-master-SNAPSHOT/gravitee-node-3.0.8-APIM-305-add-keystore-watcher-flag-master-SNAPSHOT.zip)

[master] Add config to disable keystore watcher

---

pom.xml

---
- use it directly by updating your project with version: `3.1.0-chore-bump-gravitee-plugin-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/3.1.0-chore-bump-gravitee-plugin-SNAPSHOT/gravitee-node-3.1.0-chore-bump-gravitee-plugin-SNAPSHOT.zip)

chore: bump gravitee-plugin to 2.0.0-alpha1

---

gravitee-node-cache/gravitee-node-cache-common/pom.xml
gravitee-node-cache/gravitee-node-cache-plugin-standalone/pom.xml
gravitee-node-certificates/pom.xml
gravitee-node-cluster/gravitee-node-cluster-plugin-standalone/pom.xml
gravitee-node-cluster/pom.xml
gravitee-node-notifier/pom.xml
gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/plugin/impl/NotifierPluginFactoryImpl.java
gravitee-node-services/gravitee-node-services-initializer/pom.xml
gravitee-node-services/pom.xml
pom.xml

Bump dependencies.
Supports both javax and jakarta Inject annotation in `gravitee-node-notifier`.
Upgrading gravitee-plugin to 2.0.0 brings an updated gravitee-node-api
which does not declare javax.inject dependencies anynore. This prevented
the compilation of the gravitee-node-notifier module.
This commit adds the javax.inject dependency to fix the compilation. It
also supports the new annotation comming from Jakarta.
---
- use it directly by updating your project with version: `4.0.0-bump-dependencies-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee …

chore(deps): bump dependencies

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java

related to AM-652
Addition of a feature name for the AM policy mfa-challenge
---
- use it directly by updating your project with version: `4.1.0-AM-652-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.1.0-AM-652-SNAPSHOT/gravitee-node-4.1.0-AM-652-SNAPSHOT.zip)

feat: add `am-policy-mfa-challenge` license feature for AM

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java

closes AM-653
---
- use it directly by updating your project with version: `4.2.0-AM-653-users-account-linking-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.2.0-AM-653-users-account-linking-SNAPSHOT/gravitee-node-4.2.0-AM-653-users-account-linking-SNAPSHOT.zip)

feat: add AM Account Linking policy

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java

closes AM-695
---
- use it directly by updating your project with version: `4.3.0-AM-695-mfa-support-sfr-service-to-send-sms-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.3.0-AM-695-mfa-support-sfr-service-to-send-sms-SNAPSHOT/gravitee-node-4.3.0-AM-695-mfa-support-sfr-service-to-send-sms-SNAPSHOT.zip)

feat: add AM SFR SMS resource plugin

---

pom.xml

see https://github.com/gravitee-io/gravitee-plugin/pull/119
---
- use it directly by updating your project with version: `4.3.1-fix-bump-gravitee-common-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.3.1-fix-bump-gravitee-common-SNAPSHOT/gravitee-node-4.3.1-fix-bump-gravitee-common-SNAPSHOT.zip)

fix: bump gravitee-common to 3.3.3

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/VertxServerFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/VertxServerOptions.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/http/VertxHttpServerOptions.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/tcp/VertxTcpServer.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/tcp/VertxTcpServerFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/tcp/VertxTcpServerOptions.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/server/VertxServerFactoryTest.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/server/tcp/VertxTcpServerOptionsTest.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/server/tcp/VertxTcpServerTest.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-267
TCP server factory
---
- use it directly by updating your project with version: `4.4.0-archi-267-tcp-proxy-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.4.0-archi-267-tcp-proxy-SNAPSHOT/gravitee-node-4.4.0-archi-267-tcp-proxy-SNAPSHOT.zip)

Archi 267 tcp proxy

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/VertxServerOptions.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/http/VertxHttpServerOptions.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/server/tcp/VertxTcpServerOptionsTest.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-267
moved compression option into http options
also remove usage of complex regular expression to avoid denial of service attacks
fix a few warning sonar raised
---
- use it directly by updating your project with version: `4.4.0-archi-267-vertx-option-fix-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.4.0-archi-267-vertx-option-fix-SNAPSHOT/gravitee-node-4.4.0-archi-267-vertx-option-fix-SNAPSHOT.zip)

fix: vertx options reshufling and fixes

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java

This PR introduces AE as an enterprise feature
---
- use it directly by updating your project with version: `4.5.0-feat-handle-ae-as-a-feature-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.5.0-feat-handle-ae-as-a-feature-SNAPSHOT/gravitee-node-4.5.0-feat-handle-ae-as-a-feature-SNAPSHOT.zip)

feat: allow AE as an enterprise feature

---

pom.xml

**Issue**
AM needs to use latest k8s client version following an issue during testing.
Update to gravitee-node to lastest K8s client version for AM usage.
---
- use it directly by updating your project with version: `4.6.0-update-k8s-client-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.6.0-update-k8s-client-version-SNAPSHOT/gravitee-node-4.6.0-update-k8s-client-version-SNAPSHOT.zip)

Update k8s client version

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java

**Issue**
Recent changes added alert-engine in base entreprise features pack.
When Alert Engine will adopt the node's license framework, that would have added alter engine to all "planet" licenses.
* Created a specific pack to that the feature is known in the license model
* Remove AE feature from the entreprise pack
* Add to AE feature "galaxy" and "universe" tiers
This way, when AE adapots node's license framework :
* License with "planet" tier will not infer alert-engine feature, hence it is not added by accident.
* galaxy and universe tier will include AE feature automatically.
** This does not affect the current behaviour, license generator is not impacted **
---
🚀 A prerelease version of this package has …

fix: create a pack for alert-engine

---

pom.xml

**Issue**
NA
Bump gravitee-plugin to 2.2.0
---
- use it directly by updating your project with version: `4.6.0-bump-gravitee-plugin-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.6.0-bump-gravitee-plugin-SNAPSHOT/gravitee-node-4.6.0-bump-gravitee-plugin-SNAPSHOT.zip)

Bump gravitee-plugin to 2.2.0

---

gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/JettyHttpConfiguration.java
gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/JettyHttpServer.java
gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/JettyHttpServerFactory.java
gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/healthcheck/JettyHttpServerProbe.java
gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/spring/JettyContainerConfiguration.java
gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/configuration/HttpServerConfiguration.java
gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/spring/HttpServerSpringConfiguration.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/probe/CPUProbe.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/probe/MemoryProbe.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/monitor/NodeMonitorService.java
gravitee-node-notifier/src/main/java/io/gravitee/node/notifier/NotifierServiceImpl.java
gravitee-node-services/gravitee-node-services-upgrader/src/main/java/io/gravitee/node/services/upgrader/UpgraderServiceImpl.java
gravitee-node-services/gravitee-node-services-upgrader/src/main/java/io/gravitee/node/services/upgrader/spring/UpgraderConfiguration.java
gravitee-node-services/gravitee-node-services-upgrader/src/test/java/io/gravitee/node/services/upgrader/UpgraderServiceImplTest.java
pom.xml

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-299
This PR defers most of the `@Value` and some bean instantiations in order to make them eligible for secret injection (waiting for a proper global solution).
This mainly covers the server bootstraps that are susceptible to being configured using secrets such as keystore passwords.
- Jetty server
- Vertx HTTP/TCP server
- Management Server
---
- use it directly by updating your project with version: `4.6.1-archi-299-defer-resolve-values-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/i …

fix: defer some sensitive @Value resolution

---

gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/ClusterManager.java
gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/messaging/Message.java
gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/messaging/Queue.java
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/HazelcastClusterManager.java
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/messaging/HazelcastQueue.java
gravitee-node-cluster/gravitee-node-cluster-plugin-standalone/pom.xml
gravitee-node-cluster/gravitee-node-cluster-plugin-standalone/src/main/java/io/gravitee/node/plugin/cluster/standalone/StandaloneClusterManager.java
gravitee-node-cluster/gravitee-node-cluster-plugin-standalone/src/main/java/io/gravitee/node/plugin/cluster/standalone/messaging/StandaloneQueue.java
gravitee-node-cluster/gravitee-node-cluster-plugin-standalone/src/test/java/io/gravitee/node/plugin/cluster/standalone/messaging/StandaloneQueueTest.java
gravitee-node-cluster/gravitee-node-cluster-plugin-standalone/src/test/java/io/gravitee/node/plugin/cluster/standalone/messaging/StandaloneTopicTest.java

Add queue on cluster manager with implementation for standalone or hazelcast cluster.
---
- use it directly by updating your project with version: `4.7.0-integration-foundation-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.7.0-integration-foundation-SNAPSHOT/gravitee-node-4.7.0-integration-foundation-SNAPSHOT.zip)

feat: add queue on ClusterManager

---

gravitee-node-api/src/main/java/io/gravitee/node/api/cache/Cache.java
gravitee-node-cache/gravitee-node-cache-common/src/main/java/io/gravitee/node/plugin/cache/common/InMemoryCache.java
gravitee-node-cache/gravitee-node-cache-common/src/test/java/io/gravitee/node/plugin/cache/common/InMemoryCacheTest.java
gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cache/hazelcast/HazelcastCache.java
gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/test/java/io/gravitee/node/plugin/cache/hazelcast/HazelcastCacheTest.java

- implement new methods on InMemory and Hazelcast cache implementation
---
- use it directly by updating your project with version: `4.8.0-improve-cache-api-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.8.0-improve-cache-api-SNAPSHOT/gravitee-node-4.8.0-improve-cache-api-SNAPSHOT.zip)

feat: improve Cache interface

---

gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseManagerTest.java

Add timeout in some tests when verifying the `DefaultLicenseManager` behavior.
---
- use it directly by updating your project with version: `5.0.0`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.0.0/gravitee-node-5.0.0.zip)

test: add timeout on DefaultLicenseManagerTest checks

---

gravitee-node-api/src/main/java/io/gravitee/node/api/certificate/KeyStoreLoader.java
gravitee-node-kubernetes/src/main/java/io/gravitee/node/kubernetes/keystoreloader/KubernetesConfigMapKeyStoreLoader.java
gravitee-node-kubernetes/src/main/java/io/gravitee/node/kubernetes/keystoreloader/KubernetesKeyStoreLoaderFactory.java
gravitee-node-kubernetes/src/main/java/io/gravitee/node/kubernetes/keystoreloader/KubernetesPemRegistryKeyStoreLoader.java
gravitee-node-kubernetes/src/test/java/io/gravitee/node/kubernetes/keystoreloader/KubernetesConfigMapKeyStoreLoaderTest.java
gravitee-node-kubernetes/src/test/java/io/gravitee/node/kubernetes/keystoreloader/KubernetesPemRegistryKeyStoreLoaderTest.java
pom.xml

**Issue**
https://gravitee.atlassian.net/browse/APIM-2969
---
- use it directly by updating your project with version: `5.0.1-pem-registry-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.0.1-pem-registry-master-SNAPSHOT/gravitee-node-5.0.1-pem-registry-master-SNAPSHOT.zip)

fix: update pem registry logic

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-3495
---
- use it directly by updating your project with version: `5.2.0-apim-3495-graphql-ratelimit-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.2.0-apim-3495-graphql-ratelimit-SNAPSHOT/gravitee-node-5.2.0-apim-3495-graphql-ratelimit-SNAPSHOT.zip)

feat(license): add graphql rate limit policy feature

---

gravitee-node-container/src/main/java/io/gravitee/node/container/AbstractContainer.java
gravitee-node-container/src/main/java/io/gravitee/node/container/spring/NodeContainerConfiguration.java
gravitee-node-container/src/main/java/io/gravitee/node/container/spring/SpringBasedContainer.java
gravitee-node-license/src/main/java/io/gravitee/node/license/LicenseLoaderService.java
gravitee-node-license/src/test/java/io/gravitee/node/license/LicenseLoaderServiceTest.java

**Issue**
Linked to https://gravitee.atlassian.net/browse/ARCHI-297
The `Node` bean is instantiated twice. The objective of this PR is to get rid of the `Node` bean for the bootstrap phase and only instantiate it with the beans of the application.
For that, the `DefaultLicenseService` no longer needs the `Node` bean. It was previously mandatory to stop the node when the expiration of the license is detected. It has been replaced with a simple `System.exit(0)` which triggers the stop of the node by executing the shutdown hooks of the JVM.

fix: defer node bean instantiation

---

gravitee-node-license/src/main/java/io/gravitee/node/license/DefaultLicenseManager.java
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseManagerTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-3879
When there are unknown plugins, the validator should not throw an exception.
This is necessary for the fact that the plugins that may exist in Gateway are not detected in the rest-api, and vice versa. 
---
- use it directly by updating your project with version: `5.5.2-apim-3879-allow-unknown-plugins-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.5.2-apim-3879-allow-unknown-plugins-SNAPSHOT/gravitee-node-5.5.2-apim-3879-allow-unknown-plugins-SNAPSHOT …

fix(license): allow unknown plugins during validation

---

gravitee-node-api/src/main/java/io/gravitee/node/api/cache/Cache.java
gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/messaging/Queue.java
gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/messaging/Topic.java
gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cache/hazelcast/HazelcastCache.java
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/messaging/HazelcastQueue.java
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/messaging/HazelcastTopic.java

Add reactive method on cache, Topic and Queue with default implementation and specific one with Hazelcast.
---
- use it directly by updating your project with version: `5.6.0-add-reactive-api-cache-cluster-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.6.0-add-reactive-api-cache-cluster-SNAPSHOT/gravitee-node-5.6.0-add-reactive-api-cache-cluster-SNAPSHOT.zip)

feat: add reactive method to Cache, Topic and Queue

---

gravitee-node-api/src/main/java/io/gravitee/node/api/license/ExpiredLicenseException.java
gravitee-node-api/src/main/java/io/gravitee/node/api/license/InvalidLicenseException.java
gravitee-node-license/src/main/java/io/gravitee/node/license/DefaultLicense.java
gravitee-node-license/src/main/java/io/gravitee/node/license/DefaultLicenseFactory.java
gravitee-node-license/src/main/java/io/gravitee/node/license/DefaultLicenseManager.java
gravitee-node-license/src/main/java/io/gravitee/node/license/OSSLicense.java
gravitee-node-license/src/main/java/io/gravitee/node/license/license3j/License3J.java
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseManagerTest.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-332
This PR offers better support for org licenses when they expire.
---
- use it directly by updating your project with version: `5.5.3-archi-332-support-expired-org-licenses-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.5.3-archi-332-support-expired-org-licenses-SNAPSHOT/gravitee-node-5.5.3-archi-332-support-expired-org-licenses-SNAPSHOT.zip)

fix: support org license expiration

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java

closes APIM-3616
---
- use it directly by updating your project with version: `5.7.0-APIM-3616-inter-ops-policy-qa-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.7.0-APIM-3616-inter-ops-policy-qa-SNAPSHOT/gravitee-node-5.7.0-APIM-3616-inter-ops-policy-qa-SNAPSHOT.zip)

feat: add interops features

---

gravitee-node-api/src/main/java/io/gravitee/node/api/cache/Cache.java
gravitee-node-cache/gravitee-node-cache-common/src/main/java/io/gravitee/node/plugin/cache/common/InMemoryCache.java
gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cache/hazelcast/HazelcastCache.java

Add some methods as entrySet, values, keys.
---
- use it directly by updating your project with version: `5.7.0-improve-cache-interface-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.7.0-improve-cache-interface-SNAPSHOT/gravitee-node-5.7.0-improve-cache-interface-SNAPSHOT.zip)

feat: add new cache method

---

gravitee-node-certificates/src/main/java/io/gravitee/node/certificates/AbstractKeyStoreLoaderManager.java
gravitee-node-certificates/src/main/java/io/gravitee/node/certificates/DefaultKeyStoreLoaderFactoryRegistry.java
gravitee-node-certificates/src/main/java/io/gravitee/node/certificates/TrustStoreLoaderManager.java
gravitee-node-certificates/src/test/java/io/gravitee/node/certificates/TrustStoreLoaderManagerTest.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-340
This PR fixes back the support for private ca as truststore.
---
- use it directly by updating your project with version: `5.8.1-archi-340-support-private-ca-for-truststore-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.8.1-archi-340-support-private-ca-for-truststore-SNAPSHOT/gravitee-node-5.8.1-archi-340-support-private-ca-for-truststore-SNAPSHOT.zip)

fix: support private ca as truststore

---

gravitee-node-certificates/pom.xml
gravitee-node-kubernetes/pom.xml
gravitee-node-license/pom.xml
gravitee-node-secrets/gravitee-node-secrets-service/pom.xml
gravitee-node-vertx/pom.xml
pom.xml

**Issue**
https://gravitee.atlassian.net/browse/APIM-4028
The library https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on has been moved to https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on
The library https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk15on has been moved to 
https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk18on
The main goal of this task is to update the library and resolve vulnerability issues:
https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6084022
---
- use it directly by updating your project with version: …

fix(deps): update bcprov-jdk15on to bcprov-jdk18on

---

gravitee-node-api/src/main/java/io/gravitee/node/api/license/LicenseFactory.java
gravitee-node-license/src/main/java/io/gravitee/node/license/DefaultLicenseFactory.java
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-4183
When the base64 license is null, then an OSS license is returned.
Cockpit can delete an organization license, which effectively sends a payload with `license: null`. In this case, the `create` should yield an OSS license that APIM (Gateway + MAPI) can then use in `registerOrganizationLicense`.  
---
- use it directly by updating your project with version: `5.10.0-apim-4183-handle-null-org-license-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.10.0-ap …

feat: a null license on create returns an oss license

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpClientFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpClientOptions.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/client/http/VertxHttpClientFactoryTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-3966
Add the possibility to configure the keep-alive timeout.
---
- use it directly by updating your project with version: `5.11.0-apim-3966-configure-keepalive-timeout-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.11.0-apim-3966-configure-keepalive-timeout-SNAPSHOT/gravitee-node-5.11.0-apim-3966-configure-keepalive-timeout-SNAPSHOT.zip)

feat: handle keep-alive timeout

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/http/VertxHttpServerOptions.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-4468
set http2-max-header-list-size option from the provided config
---
- use it directly by updating your project with version: `4.8.4-APIM-4468-http2-max-header-size-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.8.4-APIM-4468-http2-max-header-size-SNAPSHOT/gravitee-node-4.8.4-APIM-4468-http2-max-header-size-SNAPSHOT.zip)

fix: set http2-max-header-list-size option from the provided config

---

gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/spring/HttpServerSpringConfiguration.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpClientFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/http/VertxHttpServerOptions.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-4560
https://github.com/gravitee-io/issues/issues/9671
Configure alpn option even if not secured.
---
- use it directly by updating your project with version: `5.12.4-apim-4560-fix-alpn-configuration-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.12.4-apim-4560-fix-alpn-configuration-master-SNAPSHOT/gravitee-node-5.12.4-apim-4560-fix-alpn-configuration-master-SNAPSHOT.zip)

Configure alpn option even if not secured - master

---

gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/spring/HttpServerSpringConfiguration.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/http/VertxHttpServerOptions.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-4560
https://github.com/gravitee-io/issues/issues/9671
Configure alpn option even if not secured.
---
- use it directly by updating your project with version: `4.8.5-apim-4560-fix-alpn-configuration-4-8-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.8.5-apim-4560-fix-alpn-configuration-4-8-x-SNAPSHOT/gravitee-node-4.8.5-apim-4560-fix-alpn-configuration-4-8-x-SNAPSHOT.zip)

Configure alpn option even if not secured - 4.8.x

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java

Fixes: AM-3077
---
- use it directly by updating your project with version: `4.0.1-AM-3077-orange-plugin-v4-0-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.0.1-AM-3077-orange-plugin-v4-0-x-SNAPSHOT/gravitee-node-4.0.1-AM-3077-orange-plugin-v4-0-x-SNAPSHOT.zip)

fix: add orange contact everyone plugin

---

gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/spring/HttpServerSpringConfiguration.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/http/VertxHttpServerOptions.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-4560
This reverts commit ad5456df338311e0cad3c835387615d13d27c027.
ALPN makes no sens without TLS
---
- use it directly by updating your project with version: `4.8.6-revert-alpn-changes-4-8-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.8.6-revert-alpn-changes-4-8-SNAPSHOT/gravitee-node-4.8.6-revert-alpn-changes-4-8-SNAPSHOT.zip)

Revert ALPN changes - 4.8.x

---

gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/spring/HttpServerSpringConfiguration.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpClientFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/server/http/VertxHttpServerOptions.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-4560
This reverts commit eb54cffdac2fd1d6403f3da016517f020e0f92c1.
ALPN makes no sens without TLS
---
- use it directly by updating your project with version: `5.14.3-revert-alpn-changes-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.14.3-revert-alpn-changes-SNAPSHOT/gravitee-node-5.14.3-revert-alpn-changes-SNAPSHOT.zip)

Revert ALPN changes

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java

cherry pick from 7604631
---
- use it directly by updating your project with version: `5.14.4-mergify-add-interops-sp-plugins-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.14.4-mergify-add-interops-sp-plugins-SNAPSHOT/gravitee-node-5.14.4-mergify-add-interops-sp-plugins-SNAPSHOT.zip)

fix: add Interops SP plugins

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java

fixes AM-3293
---
- use it directly by updating your project with version: `4.3.3-mergify-bp-4-3-x-AM-3293-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.3.3-mergify-bp-4-3-x-AM-3293-SNAPSHOT/gravitee-node-4.3.3-mergify-bp-4-3-x-AM-3293-SNAPSHOT.zip)

fix: add AM HTTP resource plugin

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpClientOptions.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/client/http/VertxHttpClientFactoryTest.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-364
Remove misleading usage of Vertx Http Client Options.
During recent refactoring `io.gravitee.definition.model.v4.http.HttpClientOptions` has been mapped 1:1 with `io.gravitee.node.vertx.client.http.VertxHttpClientOptions` but some options are not  applicable.
* followRedirect cannot be used in VertxClientOptions, it is a request option. It is handled as such in proxy connector: no risk
* propagateClientAcceptHeader cannot be used in VertxClientOptions, it is proxy connector logic: no risk
*Warning* they are impact in APIM (test compile issue) hence the non breaking change nature of this PR, but a change will be requested in APIM as soon as this PR is merged.

fix: remove misleading options in vertx client factory

---

gravitee-node-api/src/main/java/io/gravitee/node/api/healthcheck/Probe.java
gravitee-node-api/src/main/java/io/gravitee/node/api/healthcheck/ProbeEvaluator.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/DefaultProbeEvaluator.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/NodeHealthCheckManagementEndpoint.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/NodeHealthCheckService.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/NodeHealthCheckThread.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/micrometer/NodeHealthCheckMicrometerHandler.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/probe/CPUProbe.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/probe/MemoryProbe.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/monitor/NodeMonitorManagementEndpoint.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/monitor/NodeMonitorService.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/monitor/NodeMonitorThread.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/spring/HealthConfiguration.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/spring/MonitoringConfiguration.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/spring/NodeMonitoringConfiguration.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/DefaultProbeEvaluatorTest.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/healthcheck/NodeHealthCheckManagementEndpointTest.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/healthcheck/NodeHealthCheckServiceTest.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/healthcheck/NodeHealthCheckThreadTest.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/healthcheck/TestingProbe.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/healthcheck/probe/CPUProbeTest.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/healthcheck/probe/MemoryProbeTest.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/monitor/NodeMonitorServiceTest.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/monitor/NodeMonitorThreadTest.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-365
This PR refactor the way the probes are evaluated by the healthcheck. It introduces a `ProbeRegistry` that is responsible for evaluating the probes and dealing with caching.
---
- use it directly by updating your project with version: `5.15.0-archi-365-reduce-repository-pressure-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.15.0-archi-365-reduce-repository-pressure-SNAPSHOT/gravitee-node-5.15.0-archi-365-reduce-repository-pressure-SNAPSHOT.zip)

feat: reduce pressure on db due to health and monitoring

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-4164
Add oas validation policy feature to license.
---
- use it directly by updating your project with version: `5.16.0-APIM-4164-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.16.0-APIM-4164-SNAPSHOT/gravitee-node-5.16.0-APIM-4164-SNAPSHOT.zip)

feat: add oas validation policy feature to license

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java

**Issue**
https://gravitee.atlassian.net/browse/AM-3308
Add secret provider aws to license model
---
- use it directly by updating your project with version: `5.18.0-feat-secretprovider-aws-license-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.18.0-feat-secretprovider-aws-license-SNAPSHOT/gravitee-node-5.18.0-feat-secretprovider-aws-license-SNAPSHOT.zip)

feat: add secret provider aws to license model

---

gravitee-node-tracing/pom.xml
pom.xml

**Issue**
https://gravitee.atlassian.net/browse/APIM-5276
OpenTelemetry dependency
---
- use it directly by updating your project with version: `5.17.0`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.17.0/gravitee-node-5.17.0.zip)

chore: add opentelemetry dependency to tracing module

---

gravitee-node-container/src/main/java/io/gravitee/node/container/spring/env/AbstractGraviteePropertySource.java
gravitee-node-container/src/test/java/io/gravitee/node/container/spring/env/WatchablePropertyResolverSubscriberTest.java

fixes AM-3317, stacktrace details in https://gravitee.atlassian.net/browse/AM-3317
StackOverflowError is thrown due to recursive loop on watchProperty().
As a remedy, the main Flowable is wrapped to Flowable.defer(Supplier) and chained with repeat()
---
- use it directly by updating your project with version: `4.3.3-AM-3317-fix-stackoverflow-ex-on-watch-loop-4-3-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.3.3-AM-3317-fix-stackoverflow-ex-on-watch-loop-4-3-SNAPSHOT/gravitee-node-4.3.3-AM-3317-fix-stackoverflow-ex-on-watch-loop-4-3-SNAPSHOT.zip …

[4.3.x] fix: recursive method call may lead to stack overflow exception

---

gravitee-node-container/src/main/java/io/gravitee/node/container/spring/env/AbstractGraviteePropertySource.java
gravitee-node-container/src/test/java/io/gravitee/node/container/spring/env/WatchablePropertyResolverSubscriberTest.java

fixes AM-3317, stacktrace details in https://gravitee.atlassian.net/browse/AM-3317
StackOverflowError is thrown due to recursive loop on watchProperty(). 
As a remedy, the main Flowable<T> is wrapped to Flowable.defer(Supplier<Flowable>) and chained with repeat() 
---
- use it directly by updating your project with version: `4.6.4-AM-3317-fix-stackoverflow-ex-on-watch-loop-4-6-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.6.4-AM-3317-fix-stackoverflow-ex-on-watch-loop-4-6-SNAPSHOT/gravitee-node-4.6.4-AM-3317-fix-stackoverflow-ex-on-watch-loop-4 …

[4.6.x] fix: recursive method call may lead to stack overflow exception

---

gravitee-node-api/src/main/java/io/gravitee/node/api/upgrader/Upgrader.java
gravitee-node-services/gravitee-node-services-upgrader/src/main/java/io/gravitee/node/services/upgrader/UpgraderServiceImpl.java
gravitee-node-services/gravitee-node-services-upgrader/src/test/java/io/gravitee/node/services/upgrader/UpgraderServiceImplTest.java

**Issue**
N/A
Improve upgrader framework to allow specifying a version and a name.
Versioning upgraders allow us to modify or fix them if required. By doing this, new versions of upgraders can be executed.
---
- use it directly by updating your project with version: `4.8.7-update-upgrader-fwk-to-customize-upgrader-name-4-8-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.8.7-update-upgrader-fwk-to-customize-upgrader-name-4-8-x-SNAPSHOT/gravitee-node-4.8.7-update-upgrader-fwk-to-customize-upgrader-name-4-8-x-SNAPSHOT.zip)

Improve upgrader framework

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java

**Issue**
https://gravitee.atlassian.net/browse/AM-3310
Add am-certificate-aws to licence model
---
- use it directly by updating your project with version: `5.19.0-feat-AM-3308-add-aws-am-certificate-plugin-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.19.0-feat-AM-3308-add-aws-am-certificate-plugin-SNAPSHOT/gravitee-node-5.19.0-feat-AM-3308-add-aws-am-certificate-plugin-SNAPSHOT.zip)

feat: add AM enterprise certificate AWS plugin

---

gravitee-node-management/src/main/java/io/gravitee/node/management/http/endpoint/ManagementEndpointManager.java
gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/endpoint/DefaultManagementEndpointManager.java
gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/verticle/ManagementVerticle.java
gravitee-node-management/src/test/java/io/gravitee/node/management/http/vertx/endpoint/DefaultManagementEndpointManagerTest.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-389
This PR add the capacity of unregistering a management endpoint.
---
- use it directly by updating your project with version: `5.20.0-archi-389-allow-to-unregister-management-endpoint-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.20.0-archi-389-allow-to-unregister-management-endpoint-SNAPSHOT/gravitee-node-5.20.0-archi-389-allow-to-unregister-management-endpoint-SNAPSHOT.zip)

feat: allow to unregister a management endpoint

---

gravitee-node-cache/gravitee-node-cache-plugin-handler/src/main/java/io/gravitee/node/cache/NodeCacheService.java
gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cache/hazelcast/HazelcastCacheManager.java
gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cache/hazelcast/spring/HazelcastCacheConfiguration.java
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/HazelcastClusterManager.java
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/spring/HazelcastClusterConfiguration.java
gravitee-node-container/src/main/java/io/gravitee/node/container/AbstractNode.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/handler/NodeMonitoringEventHandler.java

**Issue**
When analysing cockpit issue with wrong connectors status, wrong node information, it appears there were issues regarding hazelcast with cluster and cache plutins.
1. Cache plugin was not properly initialized and shutdown which could lead to a brutal hazelcast kill on k8s
2. Cache and Cluster plugin were using the same cluster and so primary member could be wrongly identified
This PR attemps to fix them both

Archi 391 fix cache manager issue

---

gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cache/hazelcast/spring/HazelcastCacheConfiguration.java
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/messaging/HazelcastQueue.java

**Issue**
When removing a subscription on a queue, the 100 timeout delay could lead the queue to take a message even if the listener has been removed. This PR attempts to fix that by waiting for the last polling to finish.
---
- use it directly by updating your project with version: `5.21.1-archi-391-fix-queue-terminaison-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.21.1-archi-391-fix-queue-terminaison-SNAPSHOT/gravitee-node-5.21.1-archi-391-fix-queue-termin …

Archi 391 fix queue terminaison

---

README.adoc
gravitee-node-api/src/main/java/io/gravitee/node/api/cache/Cache.java
gravitee-node-cache/gravitee-node-cache-common/src/main/java/io/gravitee/node/plugin/cache/common/InMemoryCache.java
gravitee-node-cache/gravitee-node-cache-common/src/test/java/io/gravitee/node/plugin/cache/common/InMemoryCacheTest.java
gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cache/hazelcast/HazelcastCache.java
gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/test/java/io/gravitee/node/plugin/cache/hazelcast/HazelcastCacheTest.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-392
This PR fixes possible `NullPointerException` when using reactive `rxPut` and `rxCompute` methods which may return null value that is not allowed with `Single`. 
BREAKING CHANGE: Method signatures have changed from `Single` to `Maybe`. An empty Maybe means 'null' in the blocking world.
---
- use it directly by updating your project with version: `6.0.0-archi-392-fix-rx-methods-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.0.0-archi-392-fix-rx-methods-SNAPSHOT/gravitee-nod …

fix: NPE using rxPut and rxCompute

---

gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/MemberListener.java

**Issue**
Add default key work on MemberListener interface to avoid being forced to implement empty method.
---
- use it directly by updating your project with version: `6.0.0`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.0.0/gravitee-node-6.0.0.zip)

refactor: add default implementation for MemberListener

---

gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cache/hazelcast/spring/HazelcastCacheConfiguration.java
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/spring/HazelcastClusterConfiguration.java

**Issue**
For some reason, the fact both instances have the same name could cause an issue even if both hazelcast instances are isolated... 🤷‍♂️

fix: ensure default hazelcast instance names are different

---

gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cache/hazelcast/HazelcastCache.java
gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cache/hazelcast/HazelcastCacheManager.java
gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/test/java/io/gravitee/node/plugin/cache/hazelcast/HazelcastCacheTest.java

**Issue**
A synchronization issue has been detected using hazelcast cache especialy when evicting (removing) an element.
---
- use it directly by updating your project with version: `6.0.4-archi-391-fix-evict-implementation-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.0.4-archi-391-fix-evict-implementation-SNAPSHOT/gravitee-node-6.0.4-archi-391-fix-evict-implementation-SNAPSHOT.zip)

Archi 391 fix evict implementation

---

gravitee-node-api/src/main/java/io/gravitee/node/api/cache/CacheException.java
gravitee-node-api/src/main/java/io/gravitee/node/api/cache/CacheManager.java
gravitee-node-api/src/main/java/io/gravitee/node/api/cache/ValueMapper.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/pom.xml
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/assembly/plugin-assembly.xml
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/RedisCache.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/RedisCacheManager.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/configuration/HostAndPort.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/configuration/RedisConfiguration.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/configuration/RedisConfigurationProvider.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/configuration/RedisOptionsFactory.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/configuration/SentinelConfiguration.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/spring/RedisCacheConfiguration.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/resources/plugin.properties
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/test/java/io/gravitee/node/plugin/cache/redis/RedisCacheTest.java
gravitee-node-cache/pom.xml
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/ssl/SslOptions.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/tcp/VertxTcpClientFactory.java

this Implement doesn't covert all the methods.
A ValueMapper interface has been added to let the cache user define how to convert the value object as a String managed by Redis.
**NOTE:** For some reason the reactive client is not working inside the plugin and lead to a NoClassDefFoundException on the Redis client whereas the non reactive "RedisClient" is working.
related-to AM-3476
---
- use it directly by updating your project with version: `6.1.0-am-3476-redis-cache-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.1.0-am-3476-redis-cache-SNAPSHO …

feat: addition of Redis as cache implementation

---

gravitee-node-cache/gravitee-node-cache-plugin-redis/pom.xml

---
- use it directly by updating your project with version: `6.2.0-fix-redis-cache-pom-version-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.2.0-fix-redis-cache-pom-version-SNAPSHOT/gravitee-node-6.2.0-fix-redis-cache-pom-version-SNAPSHOT.zip)

fix: update parent pom version in redis cache implementation

---

gravitee-node-container/src/main/java/io/gravitee/node/container/GraviteeProductInitializer.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-353
Add a new interface that can be registered very soon in the booting process and allow product self awareness.
`gravitee-cloud-initializer` can use to configure cloud settings depending on the connecting product. 
---
- use it directly by updating your project with version: `6.3.0-archi-352-identify-workload-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.3.0-archi-352-identify-workload-SNAPSHOT/gravitee-node-6.3.0-archi-352-identify-workload-SNAPSHOT. …

feat: add capability to retrieve product name early during startup

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpClientFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpClientOptions.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/client/http/VertxHttpClientFactoryTest.java

**Issue**
https://github.com/gravitee-io/issues/issues/APIM-6471
allows changing http2 multiplexing limit
---
- use it directly by updating your project with version: `6.0.5-APIM-6471-grpc-large-payloads-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.0.5-APIM-6471-grpc-large-payloads-SNAPSHOT/gravitee-node-6.0.5-APIM-6471-grpc-large-payloads-SNAPSHOT.zip)

feat(http2): allows changing http2 multiplexing

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpClientOptions.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpProxyOptions.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/client/http/VertxHttpClientFactoryTest.java

**Issue**
https://github.com/gravitee-io/issues/issues/APIM-6471
This is an additional fix to APIM°6471. This PR adds missing default builders that can cause an exception when using the `VertxHttpClientOption` builder because the default value of -1 is ignored and replaced with 0 which is forbidden by vertx.
---
- use it directly by updating your project with version: `6.0.6-fix-missing-builder-default-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.0.6-fix-missing-builder-default-SNAPSHOT/gravitee-node-6.0.6-fix-missing-builder-d …

fix: missing default builder on http client options

---

gravitee-node-certificates/src/main/java/io/gravitee/node/certificates/x509/RefreshableX509TrustManagerDelegator.java
gravitee-node-certificates/src/test/java/io/gravitee/node/certificates/x509/RefreshableX509TrustManagerDelegatorTest.java

**Issue**
APIM-6628
returned an empty array instead of null prevent NPE that allow the mTLS call to succeed.
---
- use it directly by updating your project with version: `6.4.3-APIM-6628-fix-mtls-error-when-no-truststore-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.4.3-APIM-6628-fix-mtls-error-when-no-truststore-SNAPSHOT/gravitee-node-6.4.3-APIM-6628-fix-mtls-error-when-no-truststore-SNAPSHOT.zip)

fix: return empty array of accepted issuers in trust manager

---

gravitee-node-cache/README.adoc
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/configuration/RedisConfiguration.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/configuration/RedisConfigurationProvider.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/configuration/RedisOptionsFactory.java

related to AM-3974
---
- use it directly by updating your project with version: `6.4.4-am-3974-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.4.4-am-3974-SNAPSHOT/gravitee-node-6.4.4-am-3974-SNAPSHOT.zip)

fix: make redis cache pool settings configurable

---

gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/handler/NodeMonitoringEventHandler.java

fixes AM-3909 - In preparation for introducing Degraded Mode, we noticed a flood of the same messages with useless stack traces. By default, this keeps them on one line. To revert this, the log level can be set to DEBUG.
---
- use it directly by updating your project with version: `6.4.4-fix-AM-3909-too-verbose-syncmanager-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.4.4-fix-AM-3909-too-verbose-syncmanager-SNAPSHOT/gravitee-node-6.4.4-fix-AM-3909-too-verbose-syncmanager-SNAPSHOT.zip)

fix: removed stacktrace from periodic error message

---

gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/DefaultProbeEvaluator.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/micrometer/NodeHealthCheckMicrometerHandler.java

**Issue**
https://github.com/gravitee-io/issues/issues/10070
probes results in NaN for prometheus micrometer. It's because we are not holding a strong reference to the state object
[doc](https://docs.micrometer.io/micrometer/reference/concepts/gauges.html#_why_is_my_gauge_reporting_nan_or_disappearing)
---
- use it directly by updating your project with version: `6.4.5-APIM-7113-prometheus-metrics-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.4.5-APIM-7113-prometheus-metrics-SNAPSHOT/gravitee-node-6.4.5-AP …

fix(metrics): hold strong reference to probes results in micrometer gauge

---

gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/DefaultProbeEvaluator.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/micrometer/NodeHealthCheckMicrometerHandler.java

Issue
https://github.com/gravitee-io/issues/issues/10070
Description
probes results in NaN for prometheus micrometer. It's because we are not holding a strong reference to the state object
[doc](https://docs.micrometer.io/micrometer/reference/concepts/gauges.html#_why_is_my_gauge_reporting_nan_or_disappearing)
---
- use it directly by updating your project with version: `6.0.8-APIM-7113-prometheus-metrics-6-0-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.0.8-APIM-7113-prometheus-metrics-6-0-x-SNAPSHOT/gravitee-node-6.0. …

feat(metrics): hold strong reference to probes results in micrometer gauge

---

gravitee-node-cache/gravitee-node-cache-common/pom.xml
gravitee-node-cache/gravitee-node-cache-plugin-handler/pom.xml
gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/pom.xml
gravitee-node-cache/gravitee-node-cache-plugin-redis/pom.xml
gravitee-node-cache/gravitee-node-cache-plugin-standalone/pom.xml
gravitee-node-certificates/pom.xml
gravitee-node-cluster/gravitee-node-cluster-plugin-handler/pom.xml
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/pom.xml
gravitee-node-cluster/gravitee-node-cluster-plugin-standalone/pom.xml
gravitee-node-cluster/pom.xml
gravitee-node-container/pom.xml
gravitee-node-license/pom.xml
gravitee-node-management/pom.xml
gravitee-node-monitoring/pom.xml
gravitee-node-notifier/pom.xml
gravitee-node-reporter/pom.xml
gravitee-node-secrets/pom.xml
gravitee-node-services/pom.xml
gravitee-node-tracing/pom.xml
gravitee-node-vertx/pom.xml
pom.xml

**Issue**
N/A
To allow importing gravitee-node in the dependency management section of another project's pom.
---
- use it directly by updating your project with version: `6.4.6-fix-dependency-management-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.4.6-fix-dependency-management-SNAPSHOT/gravitee-node-6.4.6-fix-dependency-management-SNAPSHOT.zip)

fix: declare all modules in dependency management

---

gravitee-node-api/src/main/java/io/gravitee/node/api/infos/NodeInfos.java
gravitee-node-monitoring/pom.xml
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/infos/NodeInfosService.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/spring/NodeMonitoringConfiguration.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/infos/NodeInfosServiceTest.java

**Issue**
https://gravitee.atlassian.net/browse/CJ-2542
For the upgrade of Cloud gateways 30 days after control plane upgrade [EPIC](https://gravitee.atlassian.net/browse/CJ-2460) we need to link data plane deployment and registered nodes on cockpit side cockpit. 
This PR add a generic additionalInformation environment variable. 
Another [task on platform team side ](https://gravitee.atlassian.net/browse/TT-5930) will add the deploymentId on addtionalInformation of dataPlane.
---
- use it directly by updating your project with version: `7.0.0-cj-2542-gateway-technical-id-SNAPSHOT`
- download it from Artifactory …

feat: add metadata property to NodeInfos

---

gravitee-node-api/src/main/java/io/gravitee/node/api/healthcheck/ProbeEvaluator.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/DefaultProbeEvaluator.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/NodeHealthCheckManagementEndpoint.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/healthcheck/NodeHealthCheckManagementEndpointTest.java

(cherry picked from commit 2f585f2e3ead2b0ef917bd327193ca68f64e7b62)
**Issue**
https://gravitee.atlassian.net/browse/APIM-7637
Report fix for filtered probe issue.
---
- use it directly by updating your project with version: `6.0.9-APIM-7637-report-fix-probe-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.0.9-APIM-7637-report-fix-probe-SNAPSHOT/gravitee-node-6.0.9-APIM-7637-report-fix-probe-SNAPSHOT.zip)

fix: return unhealthy result when a filtered prob is not found

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java

this feature key is about the CloudHSM plugin in AccessManagement
fixes AM-4162
---
- use it directly by updating your project with version: `6.7.0-am-4162-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.7.0-am-4162-SNAPSHOT/gravitee-node-6.7.0-am-4162-SNAPSHOT.zip)

feat: addition of new feature key for entreprise-secret-manager pack

---

gravitee-node-license/src/main/resources/license-model.yml

**Issue**
Add a new pack of features for the kafka gateway . This pack is not part of any tier.
---
- use it directly by updating your project with version: `7.0.0-apim-add-license-feature-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.0.0-apim-add-license-feature-SNAPSHOT/gravitee-node-7.0.0-apim-add-license-feature-SNAPSHOT.zip)

Add native kafka features pack

---

gravitee-node-license/pom.xml
gravitee-node-license/src/main/java/io/gravitee/node/license/NodeLicenseServiceImpl.java
gravitee-node-license/src/test/java/io/gravitee/node/license/NodeLicenseServiceTest.java
gravitee-node-license/src/test/resources/logback-test.xml

**Issue**
---
- use it directly by updating your project with version: `4.9.0-handle-not-existing-pack-in-license-4-8-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/4.9.0-handle-not-existing-pack-in-license-4-8-x-SNAPSHOT/gravitee-node-4.9.0-handle-not-existing-pack-in-license-4-8-x-SNAPSHOT.zip)

allow to configure unknown tier & pack in the license - 4.8.x

---

gravitee-node-license/pom.xml
gravitee-node-license/src/main/java/io/gravitee/node/license/DefaultLicenseFactory.java
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java
gravitee-node-license/src/test/resources/logback-test.xml

**Issue**
---
- use it directly by updating your project with version: `5.13.0-handle-not-existing-pack-in-license-5-12-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.13.0-handle-not-existing-pack-in-license-5-12-x-SNAPSHOT/gravitee-node-5.13.0-handle-not-existing-pack-in-license-5-12-x-SNAPSHOT.zip)

allow to configure unknown tier & pack in the license - 5.12.x

---

gravitee-node-license/pom.xml
gravitee-node-license/src/main/java/io/gravitee/node/license/DefaultLicenseFactory.java
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java
gravitee-node-license/src/test/resources/logback-test.xml

**Issue**
---
- use it directly by updating your project with version: `6.1.0-handle-not-existing-pack-in-license-6-0-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.1.0-handle-not-existing-pack-in-license-6-0-x-SNAPSHOT/gravitee-node-6.1.0-handle-not-existing-pack-in-license-6-0-x-SNAPSHOT.zip)

allow to configure unknown tier & pack in the license - 6.0.x

---

gravitee-node-license/pom.xml
gravitee-node-license/src/main/java/io/gravitee/node/license/DefaultLicenseFactory.java
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java
gravitee-node-license/src/test/resources/logback-test.xml

**Issue**
---
- use it directly by updating your project with version: `6.8.0-handle-not-existing-pack-in-license-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.8.0-handle-not-existing-pack-in-license-master-SNAPSHOT/gravitee-node-6.8.0-handle-not-existing-pack-in-license-master-SNAPSHOT.zip)

allow to configure unknown tier & pack in the license - master

---

gravitee-node-license/pom.xml
gravitee-node-license/src/main/java/io/gravitee/node/license/DefaultLicenseFactory.java
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java
gravitee-node-license/src/test/resources/logback-test.xml

**Issue**
---
- use it directly by updating your project with version: `7.0.0-handle-not-existing-pack-in-license-alpha-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.0.0-handle-not-existing-pack-in-license-alpha-SNAPSHOT/gravitee-node-7.0.0-handle-not-existing-pack-in-license-alpha-SNAPSHOT.zip)

allow to configure unknown tier & pack in the license - alpha

---

gravitee-node-secrets/gravitee-secret-provider-mock/src/main/java/io/gravitee/node/secrets/plugin/mock/MockSecretProvider.java
gravitee-node-secrets/gravitee-secret-provider-mock/src/test/java/io/gravitee/node/secrets/plugin/mock/MockSecretProviderTest.java

**Issue**
Spotted a bug in secret resolution, need to update mock-secret-provider to allow a secret to have a new key

feat: allow mock secret provider to get secrets updated

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpClientFactory.java

**Issue**
keep alive timeout was not set for http2 connection.
---
- use it directly by updating your project with version: `6.5.1-fix-http2-keepalive-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.5.1-fix-http2-keepalive-SNAPSHOT/gravitee-node-6.5.1-fix-http2-keepalive-SNAPSHOT.zip)

fix: apply keep alive to http/2 connections

---

pom.xml

Bump Kube client to 3.5.1
---
- use it directly by updating your project with version: `7.0.4-fix-bump-kube-client-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.0.4-fix-bump-kube-client-SNAPSHOT/gravitee-node-7.0.4-fix-bump-kube-client-SNAPSHOT.zip)

fix: bump kube client

---

.circleci/config.yml
gravitee-node-kubernetes/pom.xml
pom.xml

**Issue**
Orb too old for upload
---
- use it directly by updating your project with version: `7.0.5-fix-bump-orb-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.0.5-fix-bump-orb-SNAPSHOT/gravitee-node-7.0.5-fix-bump-orb-SNAPSHOT.zip)

fix: bump to orb 4.12.1

---

gravitee-node-cache/gravitee-node-cache-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cache/hazelcast/spring/HazelcastCacheConfiguration.java
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/spring/HazelcastClusterConfiguration.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-484
This option was introduced as a temporary fix for upgrading Hazelcast from v5.3 to v5.5 (see:  https://github.com/hazelcast/hazelcast/issues/26486)
When enabled, the Hazelcast cluster name is suffixed with `-hzm<major><minor>` (e.g., `graviteeio-apim-cluster-hz55`). This ensures that clusters remain distinct, preventing an infinite loop where an application embedding Hazelcast v5.5 tries to join a v5.3 cluster.
**WARNING**: The option is enabled by default but can be disabled if the application already embeds a version of node >= 6.4.1, which already includes Hazelcast >= 5.5. (cc @mariano-fernandez)
To disable it, specify the following configuration in the gravitee.yaml:
```yaml
cluster:
hazelcast: …
```

fix: avoid blocking on Hz v5.5 upgrade

---

gravitee-node-license/pom.xml
gravitee-node-license/src/main/java/io/gravitee/node/license/DefaultLicenseFactory.java
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java
gravitee-node-license/src/test/resources/logback-test.xml

Applying fix to newest 5.x version
---
- use it directly by updating your project with version: `5.21.2-fix-unknown-tier-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.21.2-fix-unknown-tier-SNAPSHOT/gravitee-node-5.21.2-fix-unknown-tier-SNAPSHOT.zip)

fix: allow to configure unknown tier & pack in the license

---

gravitee-node-license/pom.xml
gravitee-node-license/src/main/java/io/gravitee/node/license/DefaultLicenseFactory.java
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java
gravitee-node-license/src/test/resources/logback-test.xml

Applying 8ac83bf5 commit to 5.19.x
---
- use it directly by updating your project with version: `5.19.1-fix-unknown-tier-5-19-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/5.19.1-fix-unknown-tier-5-19-x-SNAPSHOT/gravitee-node-5.19.1-fix-unknown-tier-5-19-x-SNAPSHOT.zip)

fix: allow to configure unknown tier & pack in the license - 5.19.x

---

gravitee-node-cache/gravitee-node-cache-plugin-redis/src/main/java/io/gravitee/node/plugin/cache/redis/RedisCache.java
gravitee-node-cache/gravitee-node-cache-plugin-redis/src/test/java/io/gravitee/node/plugin/cache/redis/RedisCacheConnectionFailureTest.java

fixes AM-4936
cherry-pick of https://github.com/gravitee-io/gravitee-node/pull/409
---
- use it directly by updating your project with version: `7.0.9-am-4936-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.0.9-am-4936-master-SNAPSHOT/gravitee-node-7.0.9-am-4936-master-SNAPSHOT.zip)

fix: wrap connection error in a CacheException

---

gravitee-node-management/README.adoc
gravitee-node-management/pom.xml
gravitee-node-management/src/main/java/io/gravitee/node/management/http/endpoint/ManagementEndpoint.java
gravitee-node-management/src/main/java/io/gravitee/node/management/http/node/log/LoggingEndpoint.java
gravitee-node-management/src/main/java/io/gravitee/node/management/http/spring/ManagementConfiguration.java
gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/verticle/ManagementVerticle.java
gravitee-node-management/src/test/java/io/gravitee/node/management/http/node/log/LoggingEndpointTest.java
gravitee-node-management/src/test/resources/logback-test.xml

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-489
This PR aims to add a new technical endpoint that can be used to check the current logging configuration or change the logging level at runtime by specifying a list of package and a level (README has been updated with examples)
---
- use it directly by updating your project with version: `7.1.0-feat-add-loglevel-endpoint-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.1.0-feat-add-loglevel-endpoint-SNAPSHOT/gravitee-node-7.1.0-feat-add-loglevel-endpoint-SNAPSHOT.zip)

feat: add new log level endpoint

---

gravitee-node-api/src/main/java/io/gravitee/node/api/opentelemetry/Span.java
gravitee-node-opentelemetry/src/main/java/io/gravitee/node/opentelemetry/tracer/noop/NoOpSpan.java
gravitee-node-opentelemetry/src/main/java/io/gravitee/node/opentelemetry/tracer/span/OpenTelemetrySpan.java

**Issue**
https://github.com/gravitee-io/issues/issues/10511
---
- use it directly by updating your project with version: `7.1.1-APIM-9423-traceparent-otel-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.1.1-APIM-9423-traceparent-otel-SNAPSHOT/gravitee-node-7.1.1-APIM-9423-traceparent-otel-SNAPSHOT.zip)

fix: added traceparent getter in opentelemetry span

---

gravitee-node-license/src/main/resources/license-model.yml

**Issue**
https://gravitee.atlassian.net/browse/APIM-7771
Add new apim-native-kafka-policy-offloading license native-kafka feature
---
- use it directly by updating your project with version: `7.2.0-APIM-7771-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.2.0-APIM-7771-SNAPSHOT/gravitee-node-7.2.0-APIM-7771-SNAPSHOT.zip)

feat(license): add support for apim-native-kafka-policy-offloading in license-model.yml

---

README.adoc
gravitee-node-api/pom.xml
gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/ClusterInfo.java
gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/ClusterManager.java
gravitee-node-api/src/main/java/io/gravitee/node/api/cluster/Member.java
gravitee-node-cluster/gravitee-node-cluster-plugin-handler/src/main/java/io/gravitee/node/cluster/NodeClusterService.java
gravitee-node-cluster/gravitee-node-cluster-plugin-handler/src/main/java/io/gravitee/node/cluster/endpoint/ClusterEndpoint.java
gravitee-node-cluster/gravitee-node-cluster-plugin-handler/src/main/java/io/gravitee/node/cluster/healthcheck/ClusterProbe.java
gravitee-node-cluster/gravitee-node-cluster-plugin-handler/src/main/resources/META-INF/spring.factories
gravitee-node-cluster/gravitee-node-cluster-plugin-handler/src/test/java/io/gravitee/node/cluster/endpoint/ClusterEndpointTest.java
gravitee-node-cluster/gravitee-node-cluster-plugin-handler/src/test/java/io/gravitee/node/cluster/healthcheck/ClusterProbeTest.java
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/HazelcastClusterManager.java
gravitee-node-cluster/gravitee-node-cluster-plugin-hazelcast/src/main/java/io/gravitee/node/plugin/cluster/hazelcast/HazelcastMember.java
gravitee-node-cluster/gravitee-node-cluster-plugin-standalone/src/main/java/io/gravitee/node/plugin/cluster/standalone/StandaloneClusterManager.java
gravitee-node-cluster/gravitee-node-cluster-plugin-standalone/src/main/java/io/gravitee/node/plugin/cluster/standalone/StandaloneMember.java
gravitee-node-management/README.adoc

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-488
This PR adds a new technical endpoint to get information on the cluster running. The idea is to provide data that could help when we need to check the version or the members connected etc. The implementation is generic and each cluster provider need to implement some method to set the data used by the endpoint. A new probe has also been added that allows to check the health of the cluster. For the Hazelcast implementation, the probe uses the cluster state and the node state.
---
- use it directly by updating your project with version: `7.2.0-feat-add-cluster-endpoint-SNAPSHOT`
- …

feat: add new cluster endpoint and cluster health probe

---

gravitee-node-license/src/main/resources/license-model.yml

**Issue**
https://gravitee.atlassian.net/browse/APIM-8989
Add support for kafka-policy-transform-key in license yml
---
- use it directly by updating your project with version: `7.4.0-APIM-8989-add-new-kafka-policy-in-license-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.4.0-APIM-8989-add-new-kafka-policy-in-license-SNAPSHOT/gravitee-node-7.4.0-APIM-8989-add-new-kafka-policy-in-license-SNAPSHOT.zip)

feat(license): add support for kafka-policy-transform-key in license yml

---

pom.xml

**Issue**
---
- use it directly by updating your project with version: `7.4.1-update-reporter-api-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.4.1-update-reporter-api-SNAPSHOT/gravitee-node-7.4.1-update-reporter-api-SNAPSHOT.zip)

fix: update reporter-api to 1.32.3

---

gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/DefaultProbeEvaluator.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/NodeHealthCheckThread.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/healthcheck/ProbeManagerImpl.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/DefaultProbeEvaluatorTest.java
gravitee-node-monitoring/src/test/java/io/gravitee/node/monitoring/healthcheck/ProbeManagerImplTest.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-504
This PR makes sure that the same probe isn't registered twice (via Spring and manually). It also ensures that there is only 1 evaluation of probes at a time to avoid putting too much pressure.
---
- use it directly by updating your project with version: `7.4.2-archi-504-avoid-probe-duplicate-evaluations-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.4.2-archi-504-avoid-probe-duplicate-evaluations-SNAPSHOT/gravitee-node-7.4.2-archi-504-avoid-probe-duplicate-evaluations-SNAP …

fix: avoid duplicate probes and concurrent evaluations

---

gravitee-node-license/src/main/resources/license-model.yml

Reverts gravitee-io/gravitee-node#418
From Product, slight change of direction in terms of the availability of the two new AI gateway policies.
We want to make these policies open source and available to all users by default.
---
- use it directly by updating your project with version: `7.5.1-revert-418-apim9299-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.5.1-revert-418-apim9299-SNAPSHOT/gravitee-node-7.5.1-revert-418-apim9299-SNAPSHOT.zip)

Revert "feat: add new "ai-gateway" pack"

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-9561
Add agent proxy entries in the license
---
- use it directly by updating your project with version: `7.7.0-apim-9561-agent-proxy-feature-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.7.0-apim-9561-agent-proxy-feature-SNAPSHOT/gravitee-node-7.7.0-apim-9561-agent-proxy-feature-SNAPSHOT.zip)

feat: add agent-proxy entrypoint and endpoint in event native features

---

gravitee-node-license/src/main/resources/license-model.yml
gravitee-node-license/src/test/java/io/gravitee/node/license/DefaultLicenseFactoryTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-9563
rename agent-proxy license entry to fit with the protocol name
---
- use it directly by updating your project with version: `7.7.1-apim-9563-agent-to-agent-feature-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.7.1-apim-9563-agent-to-agent-feature-SNAPSHOT/gravitee-node-7.7.1-apim-9563-agent-to-agent-feature-SNAPSHOT.zip)

fix: rename agent-proxy license entry to fit with the protocol name

---

gravitee-node-api/README.adoc
gravitee-node-api/src/main/java/io/gravitee/node/api/upgrader/UpgradeStatus.java
gravitee-node-api/src/main/java/io/gravitee/node/api/upgrader/Upgrader.java
gravitee-node-api/src/main/java/io/gravitee/node/api/upgrader/UpgraderException.java
gravitee-node-services/gravitee-node-services-upgrader/src/main/java/io/gravitee/node/services/upgrader/UpgraderServiceImpl.java
gravitee-node-services/gravitee-node-services-upgrader/src/test/java/io/gravitee/node/services/upgrader/UpgraderServiceImplTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-9632
This PR modifies the handling of exceptions in the upgrader's `upgrade` method. Exceptions are now thrown and managed by the caller (`upgradeServiceImpl`) instead of being handled within the upgrader itself. A new `wrapException` method has been introduced to ensure consistent exception wrapping.
Originally the issue came from this ticket: https://gravitee.atlassian.net/browse/APIM-9518.
After a quick fix https://github.com/gravitee-io/gravitee-api-management/pull/11783, we thought it could be a good idea to avoid nested try-catch blocks and hidden Exception. Also, we want to add a way to centralize the exception handling.
---
🚀 A prerelease version of this …

Improve exception handling in upgrader logs

---

gravitee-node-api/src/main/java/io/gravitee/node/api/healthcheck/Result.java
gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/DefaultProbeEvaluator.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-517
This PR fixes an issue when evaluating a cacheable probe result. When calling /_node/health, the probes are, most of the time, not evaluated in live, but instead, a cached result is returned. The evaluation of the probes occurs every X seconds (configurable). 
Each probe result now has a timestamp to properly evaluate the elapsed time since the last time the probe was evaluated.
---
- use it directly by updating your project with version: `7.8.1-archi-517-fix-probe-evaluation-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/g …

fix: properly re-evaluate cached probe

---

gravitee-node-license/src/main/resources/license-model.yml

**Issue**
https://gravitee.atlassian.net/browse/APIM-7900
Add support for kafka-policy-virtual topics in license.
---
- use it directly by updating your project with version: `7.9.0-APIM-7900-kafka-virtual-topics-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.9.0-APIM-7900-kafka-virtual-topics-SNAPSHOT/gravitee-node-7.9.0-APIM-7900-kafka-virtual-topics-SNAPSHOT.zip)

feat(license): add support for kafka-policy-virtual topics in license

---

gravitee-node-management/src/main/java/io/gravitee/node/management/http/metrics/prometheus/PrometheusEndpoint.java
gravitee-node-management/src/main/java/io/gravitee/node/management/http/utils/ConcurrencyLimitHandler.java
gravitee-node-management/src/main/java/io/gravitee/node/management/http/utils/OffloadHandler.java
gravitee-node-management/src/main/java/io/gravitee/node/management/http/utils/SafeBufferedWriter.java
gravitee-node-management/src/main/java/io/gravitee/node/management/http/vertx/verticle/ManagementVerticle.java
gravitee-node-management/src/test/java/io/gravitee/node/management/http/utils/ConcurrencyLimitHandlerTest.java
gravitee-node-management/src/test/java/io/gravitee/node/management/http/utils/OffloadHandlerTest.java
gravitee-node-management/src/test/java/io/gravitee/node/management/http/utils/SafeBufferedWriterTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-9254
Frequent queries to the Prometheus endpoint cause memory growth that can lead to OOM errors.
---
- use it directly by updating your project with version: `6.8.2-APIM-9254-Frequent-Prometheus-endpoint-calls-cause-OOM-errors-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/6.8.2-APIM-9254-Frequent-Prometheus-endpoint-calls-cause-OOM-errors-SNAPSHOT/gravitee-node-6.8.2-APIM-9254-Frequent-Prometheus-endpoint-calls-cause-OOM-errors-SNAPSHOT.zip)

fix: Prometheus OOM error

---

gravitee-node-jetty/src/main/java/io/gravitee/node/jetty/handler/NoContentOutputErrorHandler.java
gravitee-node-opentelemetry/pom.xml
pom.xml

fixes CVE-2024-7254
---
- use it directly by updating your project with version: `7.11.1-bump-protobuf-java-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.11.1-bump-protobuf-java-SNAPSHOT/gravitee-node-7.11.1-bump-protobuf-java-SNAPSHOT.zip)

fix(deps): bump protobuf-java to 3.25.5

---

gravitee-node-opentelemetry/pom.xml
pom.xml

fixes CVE-2024-7254
---
- use it directly by updating your project with version: `7.5.5-bump-protobuf-java-7-5-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/7.5.5-bump-protobuf-java-7-5-x-SNAPSHOT/gravitee-node-7.5.5-bump-protobuf-java-7-5-x-SNAPSHOT.zip)

fix(deps): bump protobuf-java to 3.25.5 [7.5.x]

---

gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpClientFactory.java
gravitee-node-vertx/src/main/java/io/gravitee/node/vertx/client/http/VertxHttpClientOptions.java
gravitee-node-vertx/src/test/java/io/gravitee/node/vertx/client/http/VertxHttpClientFactoryTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-11272
This PR provides a way to customize Client HTTP/2 settings (connection window size, stream window size, and max frame size). At the moment, it is not possible to customize them, which can cause congestion issues when handling a large number of concurrent requests or large payloads in a single HTTP/2 connection.
---
- use it directly by updating your project with version: `7.5.7-APIM-11379-Impossible-to-increase-backend-HTTP-2-window-sizes-4-7-x-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/n …

fix: allow customizing client http2 windows
